### PR TITLE
Minor correction on photo upload

### PR DESCRIPTION
**Pull request by arnotae**
- Correction for php inspector
- Function "configure" now return result
- Function "uploadPhoto" now return id (use for update and delete)

### CODE REVIEW

**Comment by mgp25** [comment]
@arnotae can you post here the changed in `Instagram.php` since i can't view it here. I see there are a lot of changes

**Comment by arnotae** [comment]
Some phpDoc improvement
Code format (with PhpStorm)
Removed "return" after "throw exception"

**uploadPhoto** : (at the end)
```
$configure = $this->configure($upload['upload_id'], $photo, $caption);
$this->expose();
return $configure[1]['media']['pk'];
```

**configure** : (at the end)
```
return $this->request('media/configure/', $this->generateSignature($post))[1];
```

**Comment by arnotae** [comment]
@mgp25 You can see result here : https://github.com/arnotae/Instagram-API/blob/master/src/Instagram.php

**Comment by mgp25** [comment]
`1,068 additions, 1,112 `

try to only modify what you want, and can you rebase it? 

Regards

**Comment by arnotae** [comment]
I will just keep my fork with composer.

Regards

**Pull request closed without merging**
