### PR TITLE
Add ability to exclude params from signed body

### PR DESCRIPTION
**Pull request by valga**
As mentioned in #1422, sometimes we need to exclude certain params from signed body and send them as POST vars.

Usage:
```php
$request->setSignedPost(true, ['d'])->addPost('d', '0');
```

Result:
```
signed_body=...&ig_sig_key_version=4&d=0
```

### CODE REVIEW

**Comment by SteveJobzniak** [comment]
@valga Excellent! Which syntax do you prefer?

```php
$request
    ->setSignedPost(true, ['d'])
    ->addPost('d', '0');

// or...

$request
    ->addPost('d', '0', false);
```

I think I prefer the first one even though it is more verbose, because it becomes very obvious that something weird is happening via that setSignedPost call.

Although... how about...

```php
$request
    ->addUnsignedPost('d', '0');
```

And addUnsignedPost can be a simple wrapper: `$this->addPost($param, $value); $this->_unsignedPosts[] = $param;`

**Comment by mgp25** [comment]
@SteveJobzniak first one looks clean, i like it

**Comment by SteveJobzniak** [comment]
@mgp25 The 3rd one may be even better though, because the 1st method relies on us typing the lists perfectly and keeping 2 separate lists of param-names in sync.

So the 3rd method is (quoted from above):

```php
$request
    ->addUnsignedPost('d', '0');
```

And addUnsignedPost can be a simple wrapper: `$this->addPost($param, $value); $this->_excludeSigned[] = $param;`

**Comment by SteveJobzniak** [comment]
Okay so I added a commit to this PR which changes the method to:

```php
$request
    ->addUnsignedPost('d', '0');
```

It's easier and less error-prone since we don't need to manually maintain the separate array of unsigned keys this way.

**Comment by SteveJobzniak** [comment]
@mgp25 So apparently, Media::like() and unlike() needs an update with a few Unsigned POST values. We can now use this `$request->addPost->('foo', 'bar')->addUnsignedPost('d', '0');` to solve that.

**Comment by andrewostroumov** [comment]
@valga what is d with value 0 param? Is this need to add to like function as unsigned param?

**Comment by SteveJobzniak** [comment]
@andrewostroumov Nope. Mgp25 has updated to the latest parameters (check commits). `d` was not used there.

**Comment by valga** [comment]
@mgp25 just forgot about it. `d` is double tap flag.

**Comment by SteveJobzniak** [comment]
@valga Ahh so `d` is used when the user double-taps the image to like it (instead of pressing the heart icon manually)? Then we don't need `d`.

**Comment by valga** [comment]
`d=1` when like is done via double tap and `d=0` when like is done via heart icon. So it is always required.

**Comment by SteveJobzniak** [comment]
@valga Well, mgp used the latest APK to check the parameters and he said it doesn't have that param. Hmm.

@mgp25 Want to comment? :)

**Comment by mgp25** [comment]
I haven't tested liking with double tap, i dont think its required if we have already this one with the heart icon. Nevertheless, we can do another function called `doubleTapLike()` but i think it isnt required.

Thoughts? @SteveJobzniak @valga

**Comment by valga** [comment]
@mgp25 Please post a captured POST body for like call made with your APK. You can strip signed body.

**Comment by mgp25** [comment]
@valga will check tomorrow, maybe i missed it.

**Comment by mgp25** [comment]
@valga yup, i can confirm what you have said. Nevertheless, i want to discuss something in private. If you want send me an email or we can create a private chat in gitter.

Regards

**Comment by valga** [comment]
@mgp25, don't forget to add that unsigned param to like/unlike methods.

**Comment by mgp25** [comment]
@valga yup, im checking and automatizing a couple of things and ill add them later tonight :p

**Pull request merged**
