### PR TITLE
Request/Live: Post live viewers list and fixes for responses

### PR DESCRIPTION
**Pull request by solomax2014**

### CODE REVIEW

**Comment by mgp25** [comment]
@solomax2014 is `getPostLiveViewerList()` a not signed request? no extra post param?

**Comment by solomax2014** [comment]
@mgp25, I don't know about signing, I think if these two methods don't require it, so this doesn't require it also. The request works fine. Yes, there is a ```max_id``` param, that I forgot, I'm going to fix it now.

**Comment by solomax2014** [comment]
@mgp25, ok, I've added ```max_id``` param. Unfortunately, I don't have so many users to test it, but I think it works like in other functions.

**Comment by mgp25** [comment]
@solomax2014 im going to merge it since its okay, but let me know where in the app should i go, to double check if everything is fine.

Regards

**Comment by solomax2014** [comment]
@mgp25, it is the eye button (bottom left) (if you are the owner of this post live). Or try to slide up the screen to see it.

**Pull request merged**
