### PR TITLE
update Dockerfile

### PR DESCRIPTION
**Pull request by mattes**
* switch to ubuntu:xenial for easy ffmpeg installation
* remove comments

### CODE REVIEW

**Comment by ilyk** [comment]
what's the problem to install `ffmpeg` on debian instead of ubuntu?

**Comment by mattes** [comment]
In debian:jessie ffmpeg is only available in backports. On top of that `php:7.0-apache` installs apache, which is not needed.

**Comment by SteveJobzniak** [comment]
Docker is not something I've ever used so I cannot review this contribution.

We need more feedback from docker users explaining why this is a good idea. To me it looks like the new Dockerfile contributed here forces users to be running Ubuntu Xenial and that's terrible if that's the case. There are thousands of Linux distros.

**Comment by SteveJobzniak** [comment]
Again: This won't get merged without more explanation. So we'll have to close this pull request for now.

**Pull request closed without merging**
