### PR TITLE
Unified inbox is not an experiment anymore

### PR DESCRIPTION
**Pull request by valga**
So we must always send `use_unified_inbox` param.

### CODE REVIEW

**Comment by SteveJobzniak** [comment]
Nice, very clear commit here. I just wonder why `hasUnifiedInbox()` is not removed? The function is not called anywhere anymore and the experiment it checks for is not stored after this change. So the function should be deleted too, right?

**Comment by valga** [comment]
I just forgot about it. Removed. Don't forget to squash this PR.

**Comment by mgp25** [comment]
@valga version?

**Comment by valga** [comment]
@mgp25, since 10.24.0.

**Comment by mgp25** [comment]
@valga perfect, everything seems okay and ready to merge.

**Comment by SteveJobzniak** [comment]
👍

**Pull request merged**
