### PR TITLE
Add proxy support

### PR DESCRIPTION
**Pull request by htaka86**
Please review.

### CODE REVIEW

**Comment by Vasiliy-Bondarenko** [comment]
Proxy support is very important feature. Why you reject this pull?

**Comment by Vasiliy-Bondarenko** [comment]
And by the way - i've tested it - it works quite well.

**Comment by mgp25** [comment]
Very important for spammers, if you want to add it to your script add it, your are free to do it, but not in the github release

**Comment by Vasiliy-Bondarenko** [comment]
why spammers? i'm making comment tracker. it's not spam in any sence :)
to add proxy support i must extend the class and replace full content of all functions using curl. because you give no way to alter the behavior of that functions. not very convenient :) or i'm missing something?

**Comment by mkanker** [comment]
Let me know...
Instagram blocks your ip when you're doing some spam?



Em dom, 1 de mai de 2016 às 08:31, Vasiliy-Bondarenko <
notifications@github.com> escreveu:

> why spammers? i'm making comment tracker. it's not spam in any sence :)
> to add proxy support i must extend the class and replace full content of
> all functions using curl. because you give no way to alter the behavior of
> that functions. not very convenient :) or i'm missing something?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mgp25/Instagram-API/pull/104#issuecomment-216036010>
>
-- 
Michel Ank

**Comment by Vasiliy-Bondarenko** [comment]
I don't know. I never did. Do you really think everyone who is working
commercially with instagram is a spammer? :)
I'm making a service to make people's life easier. What's wrong with it?

пн, 2 мая 2016 г. в 20:50, Mr Anker <notifications@github.com>:

> Let me know...
> Instagram blocks your ip when you're doing some spam?
>
>
>
> Em dom, 1 de mai de 2016 às 08:31, Vasiliy-Bondarenko <
> notifications@github.com> escreveu:
>
> > why spammers? i'm making comment tracker. it's not spam in any sence :)
> > to add proxy support i must extend the class and replace full content of
> > all functions using curl. because you give no way to alter the behavior
> of
> > that functions. not very convenient :) or i'm missing something?
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/mgp25/Instagram-API/pull/104#issuecomment-216036010>
> >
> --
> Michel Ank
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/mgp25/Instagram-API/pull/104#issuecomment-216240788>
>
-- 
// Vasiliy A Bondarenko

**Comment by mkanker** [comment]
Vasilly, why do you want to use proxy?

**Comment by Vasiliy-Bondarenko** [comment]
Because it's impossible to track comments from hundreds and thousands
accounts without proxy. And even more impossible to post answers to this
comments. :)

вт, 3 мая 2016 г. в 2:29, Mr Anker <notifications@github.com>:

> Vasilly, why do you want to use proxy?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/mgp25/Instagram-API/pull/104#issuecomment-216336780>
>
-- 
// Vasiliy A Bondarenko

**Comment by mkanker** [comment]
What did it happen when trying without proxy?

On Mon, May 2, 2016, 23:19 Vasiliy-Bondarenko <notifications@github.com>
wrote:

> Because it's impossible to track comments from hundreds and thousands
> accounts without proxy. And even more impossible to post answers to this
> comments. :)
>
> вт, 3 мая 2016 г. в 2:29, Mr Anker <notifications@github.com>:
>
> > Vasilly, why do you want to use proxy?
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/mgp25/Instagram-API/pull/104#issuecomment-216336780>
> >
> --
> // Vasiliy A Bondarenko
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/mgp25/Instagram-API/pull/104#issuecomment-216418378>
>
-- 
Michel Ank

**Pull request closed without merging**
