### PR TITLE
implement getHashtagFeed and getLocationFeed

### PR DESCRIPTION
**Pull request by milesrichardson**
get feed for given hashtag (via hashtag string) or location (via location ID)

support pagination

### CODE REVIEW

**Comment by Enelar** [comment]
What point make return after throw?

**Comment by TeymurNurullaev** [comment]
How to search location name?

**Comment by milesrichardson** [comment]
@Enelar I copied the convention already used in the `getUserFeed` call. PHP is not my strong suit so I didn't want to change anything too drastically.

**Comment by TeymurNurullaev** [comment]
@milesrichardson Can you tell me please, how to make a search by the name of location?

**Comment by milesrichardson** [comment]
@TeymurNurullaev When you call the `fbUserSearch` method, it returns a list of `hashtags`, `places`, and `users`. In the list of `places`, you want `place.location.pk` (`pk` stands for `primary key`). 

```json
 "places": [
        {
            "place": {
                "location": {
                    "address": "123 Main St, Mainville",
                    "city": "",
                    "external_id": 1230394,
                    "external_source": "facebook_places",
                    "facebook_places_id": 1234567890,
                    "foursquare_v2_id": null,
                    "lat": 36.928402825,
                    "lng": -65.194826735,
                    "name": "The Name of the Place",
                    "pk": 1234,
                    "state": ""
                },
                "media_bundles": [],
                "subtitle": "123 Main St, Mainville",
                "title": "The Name of the Place"
            },
            "position": 6
        },
        ...
]
```

So in the example above, the location ID is `1234`.

**Comment by TeymurNurullaev** [comment]
Thank you very much)))

**Pull request merged**
