### PR TITLE
Add Missing 'total_igtv_videos' and 'total_ar_effects' properties to User.php

### PR DESCRIPTION
**Pull request by Pezhvak**
add missing 'total_igtv_videos' and 'total_ar_effects' properties which seems to be new and not added to this file

### CODE REVIEW

**Comment by JRoy** [comment]
Hi @Pezhvak, you didn't place the methods in alphabetical order in the phpdoc. Please do so before I can merge.

**Comment by Pezhvak** [comment]
done

**Comment by JRoy** [comment]
Everything looks good, while you're at it though, do you mind adding the following as well:

`live_subscription_status` (string)
`is_interest_account` (bool)
`has_recommend_accounts` (bool)
`highlight_reshare_disabled` (bool)
`show_account_transparency_details` (bool)

if you can't no biggie, just let me know

**Comment by Pezhvak** [comment]
no problem at all, give me a minute

**Comment by JRoy** [comment]
Please alphabetize methods once more in each class as well as fix the issues with the style guidelines: https://github.styleci.io/analyses/XVd1jw

**Comment by Pezhvak** [comment]
alright i'm checking it

**Comment by Pezhvak** [comment]
all done

**Comment by JRoy** [comment]
Okay, you fixed this issue but totally obliterated the spacing and such. I'll fix that, however.

**Comment by Pezhvak** [comment]
i can do it now if you want

**Comment by Pezhvak** [comment]
done ^_^ sorry bad configuration in my IDE

**Comment by JRoy** [comment]
Okay, changes look good @Pezhvak thanks for your contribution!

**Comment by Pezhvak** [comment]
thank you, i will continue to do so ^_^ this is a great library 👍

**Pull request merged**
