### PR TITLE
New Feature: About This Account Support

### PR DESCRIPTION
**Pull request by JRoy**
This pull request adds full support for viewing the account information/former usernames/active ads/accounts with similar followers of business accounts (with an arbitrary amount of followers). 

This is emulating the "About This Account" button in the 3-dot-menu on an account's page.

These endpoints have been fully tested.

**Please only merge this once #2458 is merged,** or merge this one first I don't care. But I'll need to resolve the conflicts in the People class most likely before a merge. 

Examples:
```php
$targetId = "1639417625";

$pastNames = $ig->people->getFormerUsernames($targetId);
$sharedFollowers = $ig->people->getSharedFollowers($targetId);
$feedAds = $ig->people->getActiveFeedAds($targetId);
$storyAds = $ig->people->getActiveStoryAds($targetId);

// Get the most recent username change
print $pastNames->getFormerUsernames()[0]->getFormerUsername() . PHP_EOL;

// Get the followers overlap of one of the shared followers
print $sharedFollowers->getUsers()[0]->getOverlapScore() . PHP_EOL;

// Get the array of feed and story ads
var_dump($feedAds->getFeedItems());
var_dump($storyAds->getReels());
```

### CODE REVIEW

**Comment by JRoy** [comment]
This pull request is ready to merge, pending #2458's merge and conflicts be resolved.

**Comment by JRoy** [comment]
@mgp25 Currently the business class is all methods that cannot be used with accounts other than your own, while these methods work with any account so that's why I placed them here. If you want me to move them that's fine though.

**Comment by mgp25** [comment]
@JRoy Oks, leave them in `People` class 😄 If we change our minds we can change it later. And since the endpoint is `/users/` it makes more sense to be in `People`

Regards

**Comment by JRoy** [comment]
@mgp25 Great, would you like to merge this or close friends pr first?

**Pull request merged**
