### PR TITLE
Added support for non-square pictures.

### PR DESCRIPTION
**Pull request by projectbetaalpha**
I found a format error when I tried to upload a non-square picture. Here's the very simple fix.

### CODE REVIEW

**Comment by mgp25** [comment]
@projectbetaalpha have you tried it? Can you post a debug log?

**Comment by projectbetaalpha** [comment]
Nah, sorry, non-square pics still don't work. I misread the logs. Please disregard the PR.

**Comment by ivrb** [comment]
I tried it. It works! 
image scale ratio have to be <= 1,33

**Comment by projectbetaalpha** [comment]
That's awesome, @ivrb, thanks. I would have swore I saw it working, but never managed to get it to work again. I guess the ratio was the reason! :smile:

**Pull request closed without merging**
