### PR TITLE
Update to 42.0.0.19.95

### PR DESCRIPTION
**Pull request by mgp25**
This PR contains major changes in the prelogin and login flow. This PR contains requests from newer versions but are yet compatible with the current API version.

- I have introduced the new API URL (.b.i) - I have set it as version 3 (Constants.php).

### CODE REVIEW

**Comment by mgp25** [comment]
@valga sure! Got the point in the email. That was clever 😋 Will be ready tonight for the changes of zr!

**Comment by aitte2** [comment]
Wow I don't understand much of it... :D All this v3 and zero rewrite and b.i stuff is very confusing. xD

**Comment by mgp25** [comment]
@aitte2 Valga and I noticed this quite a long ago but did nothing to it. Lately we were working on updating requests to newer versions and talked about what `.b.i.` could be used for.

Just so you know, when you capture the requests Instagram, it was changing from `.b.i.` to `i.` and we didn't know why. Valga did a research and found the final rewrite rules.

This is a default rewrite rule for zero rating (it's a feature that gives a free traffic for mobile users).

**Comment by aitte2** [comment]
@mgp25 Thanks man for the help in understanding. 😍  If I understood right: They used `b.i` as a "special mobile traffic" domain name, and it was not a new API at all?

**Comment by mgp25** [comment]
@aitte2 yes, thats right

**Comment by valga** [comment]
@mgp25 Do you have something to add (other than consts)?

**Comment by mgp25** [comment]
@valga there you go. Ready to merge

**Comment by valga** [comment]
@mgp25 Done!

**Pull request merged**
