### PR TITLE
Direct: added new parameter for sending hidden links

### PR DESCRIPTION
**Pull request by iwex**
Sometimes it's useful to send links which are hidden in the main text.

### CODE REVIEW

**Comment by iwex** [comment]
`composer codestyle` is different than `styleci`

**Comment by JRoy** [comment]
Hi, is this feature on the Android app, if so how do I trigger this?

**Comment by iwex** [comment]
@JRoy Hi!
It works only through API, you can't send it directly over the app.

**Comment by iwex** [comment]
I will look like
image

**Comment by JRoy** [comment]
I swear I've seen this in the app before, but I don't remember how to do it. Until we can figure out how this is triggered via the app, I don't want to add this as this API is supposed to emulate the Android App.

**Comment by iwex** [comment]
@JRoy It's backward compatible, so why not to add this functionality?

**Comment by JRoy** [comment]
Whether it works or not is against the point, if it doesn't actually happen in the app, we like to avoid it

**Comment by iwex** [comment]
@JRoy, @mgp25 said "However, we can document these changes in the wiki so anyone under their own risks can perform this."
I don't have access to Wiki pages, so should I add just a comment to PhpDoc?

**Comment by iwex** [comment]
```php
$ig->direct->sendText($recipients, $text, array $options = [], $hiddenUrls = []);
```
If `$text` contains a link, it will be processed and sent as a link.

Instagram allows sending links which will be hidden from the message body. **This functionality is not present in the official Instagram application, so use it on your own risk!**
To send hidden links - just pass them as $hiddenUrls (array) parameter.

**Pull request closed without merging**
