### PR TITLE
Add workaround for ffmpeg bug when padding to odd/uneven size

### PR DESCRIPTION
**Pull request by javilumbrales**
Hey!! Here I am again :)
I've been testing the `VideoResizer` (really awesome work by the way :)) and stumbled upon with this really odd issue while resizing one video:

Command generated/executed by the `MediaAutoResizer`:

    ffmpeg -y -i 'path/to/video.mp4' -vf 'crop=w=1280:h=720:x=0:y=0,scale=w=720:h=405,pad=w=720:h=405:x=0:y=0:color=0xFFFFFF' -c:a copy -f mp4 'path/to/tmp' 2>&1

Output error:

    [Parsed_pad_2 @ 0x7fbf72700f20] Input area 0:0:720:405 not within the padded area 0:0:720:404 or zero-sized
    [Parsed_pad_2 @ 0x7fbf72700f20] Failed to configure input pad on Parsed_pad_2
    Error reinitializing filters!
    Failed to inject frame into filter network: Invalid argument
    Error while processing the decoded data for stream #0:0
    Conversion failed!

The `MediaAutoResizer` is working fine, but It seems that ffmpeg fails when padding to an odd width/height.

I've very little to none knowledge about ffmpeg and how it works, but doing some research I found an open ticket of a bug in ffmpeg which I think it's the same issue that I'm facing (https://trac.ffmpeg.org/ticket/1618).

Now, while this isn't really a problem of `MediaAutoResizer`, since it relies on `ffmpeg` I reckon it still makes sense to cope for this edge cases, so I've tried to commit a fix (basically add/subtract 1 if number is odd). It looks like it works, but given the ticket reported in ffmpeg.org, seems that this issue could happen as well if the width is an odd number. Tried to find a place to put the fix but was unsure of where to do it... if you can point me to the right place I'll commit the changes.

Also if this is not in the right place for the height fix, let me know and I'll move it elsewhere...

Regards,
Javier

### CODE REVIEW

**Comment by aitte2** [comment]
Good discovery.

@valga is responsible for the videoresizer. and I think you put the code in th wrong place. It should be in VideoResizer not in MediaAudioResizer otherwise your tweak affects photos too.

**Comment by javilumbrales** [comment]
Absolutely right 😅, I've moved it to the VideoResizer but in there I had no way to tell whether I should sum or subtract so this is still not valid for all cases.. hopefully @valga can come up with a better solution.

**Comment by valga** [comment]
@javilumbrales Original placement was right: you just need to add `isMod2Required()` method to `ResizerInterface`. It should return `true` for video and `false` for photo.

And yes, mod2 is required for x264, so we need to overcrop (overpad) both width and height. It's a bit tricky, so I don't have a nice solution yet.

**Comment by aitte2** [comment]
@valga Okay so like this...

ResizerInterface: `isMod2Required()`

VideoResizer: return true
PhotoResizer: return false

But in mediaautoresizer the original code location was wrong. It only runs that code (where javil put it) if the input width is > max.

Something else is needed. And as you say it sounds like both width and height must be tweaked.

Please take this task, your skill is needed here :D

**Comment by valga** [comment]
Sorry, but I have no time for it right now.

But if anyone will carry this task, a complete set of PHPUnit tests is required for calculations. Because `MediaAutoResizer` has become too complex to handle.

**Comment by SteveJobzniak** [comment]
I doubt that people realize what an utterly retarded algorith will be needed here nad how it risks destroying the class. We already have a super complex, very difficult and fine-tuned algorithm for perfectly adjusting aspect ratios to be 100% sure that the result is a totally valid aspect ratio. A single pixel error can lead to illegal ratios that Instagram will reject (will refuse that upload). We had to fix such calculation errors in the past.

Now we need to somehow make that super complex algorithm also cut away extra pixels to make things mod2 while somehow still keeping the perfect aspect ratio that we just carefully calculated... oh my god.

The proper fix would be if x264 supported "pad non-mod2 videos by repeating the outer pixel edge once for each of the non-mod2 edges, and then add a playback tag to tell the player to crop away the padding on-decode. But it looks like that is not supported by the H264 standard. Only the MKV Container format supports that solution.

I have some ideas for an algorithm that can apply post-cropping of the target canvas while aiming at the legal aspect ratio range. But as I told @mgp25 I will not start _any_ more work until after https://github.com/mgp25/Instagram-API/pull/1619 is merged (it has been open for 2 days). And if I recover from my fever before that, then I simply won't do it, since I am only messing around here again due to being trapped in bed with 39-40C FEVER... :-/ So if you want the feature, just make sure to hurry up with merging the current work.

**Comment by SteveJobzniak** [comment]
Okay since I'm still sick, I only had energy for about 1 hour of tinkering with this today. I'm nearly done with the algorithm. All of the accurate mod2 re-calculation code is complete. It just needs to handle adjusting the crop "copy from source" and "shift" coordinates based on the new canvas size we arrived at (if canvas shrunk, we'll simply crop more to remain at 1:1 pixel ratio for a sharp image; if canvas grew, we'll increase source-pixel copying as much as possible if more pixels were available in the original source, etc...). That last step is a bit tricky so I have no energy to think about it today. I may even commit this with the `isMod2Required()` + mod2-calculation code but not the CROP re-calculations, simply because I wasn't even supposed to be here. I just did some extra work due to being sick, but now I'm very tired... ;p Either way, you guys will soon have a finished or nearly-finished implementation in your hands.

**Comment by SteveJobzniak** [comment]
https://github.com/SteveJobzniak/Instagram-API/commit/b62116d9a695d0fc803c7c752e0856dab4809e65

Output:

```
[[During all of these tests, I hardcoded width=721 as input,
to force the mod2-fixer to run. Because our regular algorithm
was already consistently choosing width=720.]]

----


REGULAR DATA TESTS (this is the normal operation
                    people will see during regular
                    usage; it never needs any "Height
                    Mod2Ratio" steps since it hits
                    a legal ratio instantly)

input = 1920x1080 (1.777777778 ratio)
min & max ratio = 1 (square)

[MOD2_PROGRESS: Current Canvas Size] w=721 h=720 (ratio 1.00139)
[MOD2_PROGRESS: Width Mod2Fix] w=720 h=720 (ratio 1.00000)
[MOD2_PROGRESS: Height Recalc] w=720 h=720 (ratio 1.00000)


some other random tests with various min or max ratio values,
which shows it correctly aiming at the necessary ratio and succeeding:


[MOD2_PROGRESS: Current Canvas Size] w=721 h=641 (ratio 1.12480)
[MOD2_PROGRESS: Width Mod2Fix] w=720 h=641 (ratio 1.12324)
[MOD2_PROGRESS: Height Recalc] w=720 h=641 (ratio 1.12324)
[MOD2_PROGRESS: Height Mod2Fix] w=720 h=642 (ratio 1.12150)


[MOD2_PROGRESS: Current Canvas Size] w=721 h=600 (ratio 1.20167)
[MOD2_PROGRESS: Width Mod2Fix] w=720 h=600 (ratio 1.20000)
[MOD2_PROGRESS: Height Recalc] w=720 h=600 (ratio 1.20000)


[MOD2_PROGRESS: Current Canvas Size] w=721 h=665 (ratio 1.08421)
[MOD2_PROGRESS: Width Mod2Fix] w=720 h=665 (ratio 1.08271)
[MOD2_PROGRESS: Height Recalc] w=720 h=665 (ratio 1.08271)
[MOD2_PROGRESS: Height Mod2Fix] w=720 h=666 (ratio 1.08108)

----


EXTREME TESTS TO SHOW THE SECONDARY RATIO-CORRECTING ALGORITHM,
WHICH KICKS IN WHEN THE USER HAS SPECIFIED VERY NARROW
RANGES OF ALLOWED RATIOS... IT ADJUSTS THE HEIGHT CONTINUOUSLY
EITHER UP OR DOWN IN STEPS OF +/- 2 TO REACH A LEGAL RATIO.
IN NORMAL CASES THIS SUCCEEDS IN AT MOST ONE OR TWO TRIES, BUT
I GAVE IT SOME TOTALLY IMPOSSIBLE RATIOS TO MAKE IT FAIL 100%,
TO SHOW OFF THE DIRECTION THE ALGORITHM "CRAWLS" EACH ATTEMPT.


input = 1920x1080 (1.777777778 ratio)
min & max ratio = 1.0838238 (an impossible ratio to show that
                             algorithm will correctly go down
                             and down to lower ratios, due to
                             being programmed to aim to be "below
                             maximum" when input was above it)

[MOD2_PROGRESS: Current Canvas Size] w=721 h=665 (ratio 1.08421)
[MOD2_PROGRESS: Width Mod2Fix] w=720 h=665 (ratio 1.08271)
[MOD2_PROGRESS: Height Recalc] w=720 h=665 (ratio 1.08271)
[MOD2_PROGRESS: Height Mod2Fix] w=720 h=666 (ratio 1.08108)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=668 (ratio 1.07784)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=670 (ratio 1.07463)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=672 (ratio 1.07143)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=674 (ratio 1.06825)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=676 (ratio 1.06509)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=678 (ratio 1.06195)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=680 (ratio 1.05882)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=682 (ratio 1.05572)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=684 (ratio 1.05263)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=686 (ratio 1.04956)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=688 (ratio 1.04651)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=690 (ratio 1.04348)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=692 (ratio 1.04046)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=694 (ratio 1.03746)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=696 (ratio 1.03448)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=698 (ratio 1.03152)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=700 (ratio 1.02857)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=702 (ratio 1.02564)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=704 (ratio 1.02273)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=706 (ratio 1.01983)
- here it gives up after 20 attempts of not finding anything
  that satisfies both minimum and maximum ratio requirements -


input = 1920x1080 (1.777777778 ratio)
min&max = 1.85 (an impossible ratio to show that algorithm
                will correctly go up and up and up to higher
                ratios, due to being programmed to aim to be
                "above minimum" when input was below it)

[MOD2_PROGRESS: Current Canvas Size] w=721 h=389 (ratio 1.85347)
[MOD2_PROGRESS: Width Mod2Fix] w=720 h=389 (ratio 1.85090)
[MOD2_PROGRESS: Height Recalc] w=720 h=389 (ratio 1.85090)
[MOD2_PROGRESS: Height Mod2Fix] w=720 h=388 (ratio 1.85567)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=386 (ratio 1.86528)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=384 (ratio 1.87500)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=382 (ratio 1.88482)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=380 (ratio 1.89474)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=378 (ratio 1.90476)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=376 (ratio 1.91489)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=374 (ratio 1.92513)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=372 (ratio 1.93548)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=370 (ratio 1.94595)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=368 (ratio 1.95652)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=366 (ratio 1.96721)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=364 (ratio 1.97802)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=362 (ratio 1.98895)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=360 (ratio 2.00000)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=358 (ratio 2.01117)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=356 (ratio 2.02247)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=354 (ratio 2.03390)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=352 (ratio 2.04545)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=350 (ratio 2.05714)
[MOD2_PROGRESS: Height Mod2Ratio] w=720 h=348 (ratio 2.06897)
- here it gives up after 20 attempts of not finding anything
  that satisfies both minimum and maximum ratio requirements -
```

More commits to come, because the resizer rewrites are not done. I need to add the mentioned crop-adjustments, as well as some other checks that ensure we actually have valid values before finally proceeding (which is a necessary check even when Mod2 was not required).

**Comment by javilumbrales** [comment]
wow! I knew it had to be more complex than what I did but didn't expect it to be THAT complex! 😅 

Awesome work! I hope you get recovered soon.

All the best,
Javier

**Comment by javilumbrales** [comment]
PS: I wanted to help with this somehow, but turns out this task is miles beyond my knowledge... so I don't think I could be any useful here :(. Anyway, let me know if there's something I can do, like testing with different videos/resolutions or whatever and I'll try.

J

**Comment by SteveJobzniak** [comment]
Hi. Thank you for the well wishes. I'm starting to recover. No fever today. Still in bed though with a mean cough and tired...

I'm working on the MediaAutoResizer at the moment. Massive rewrite which makes everything clearer and much stricter. Lovely stuff. I'm also adding code-sanity checks everywhere so that any slight incorrect changes to the algorithm will be detected by the algorithm itself.

https://github.com/mgp25/Instagram-API/pull/1619/commits

When it's done, you can definitely help out by testing with various files. But the algorithms are the same for pictures and videos so it won't achieve much except having fun with some tests and cheering when it works nicely. :-)

I am not kidding about this rewrite being big. Here's a summary-view of just the MediaAutoResizer file's changes (where you can peek at some new features):

https://github.com/mgp25/Instagram-API/pull/1619/files#diff-e7d4d7bd91d92180f3594454cc5902f5

It's not done yet. But very little work remains.

**Comment by SteveJobzniak** [comment]
@javilumbrales 

> wow! I knew it had to be more complex than what I did but didn't expect it to be THAT complex!

And now... 3 hours of work later... it's even more complex... I present to you... "Woah":

https://github.com/mgp25/Instagram-API/pull/1619/commits/434a89bd0474db6707f70e939c2dff81017192de

See this is the kind of thing I meant when I said "I don't think anyone realizes how insanely complex the algorithm will have to be to successfully cut/add pixels to make a Mod2 result while _simultaneously_ aiming at a perfectly valid aspect ratio". ;-)

Anyway, this new algorithm is final now. It analyzes multiple options and picks the highest-quality solution. Phew.

**Comment by SteveJobzniak** [comment]
Okay my final MediaAutoResizer-related commit was just added... and it takes the new "Woah" prize:

https://github.com/mgp25/Instagram-API/pull/1619/commits/c505415480be054a2f3f129071a53865fc1d2e85

I hope you are happy, because _all_ of this new complexity is due to Mod2 algorithms. They complicate literally everything and have taken 2 full days to re-implement properly. But hey, it's cool, the feature is important so thanks for reporting it! :-D 👍

**Comment by javilumbrales** [comment]
Woah!!!! 😄 
Very nice work, also all the comments in the code are really helpful to get an idea or what is actually going on! I'll try to find some spare time to test it with a few videos of different resolutions, I'm sure it will be all fine! A massive thank you for your great job done 👍

**Comment by SteveJobzniak** [comment]
@javilumbrales Thanks. I've restored my push-access to the repo and will be merging the stuff today... I'll close this then :)

**Comment by SteveJobzniak** [comment]
@javilumbrales Okay Javier, all of the work is now cleanly merged into master.

https://github.com/mgp25/Instagram-API/commits/master

Enjoy and have fun checking it out. :-) Be sure to run with `$options['debug'] = true;` in MediaAutoResizer to see what it's doing. ;-)

**Comment by javilumbrales** [comment]
Hey! I hope you are well. Really sorry for not getting back to you earlier, been on holidays recently and then really busy at work so I haven't even had a chance to test it yet! Anyway, thank you very much, Iooking forward to see how it works, it's looking super-complicated, but great :D

**Comment by SteveJobzniak** [comment]
@javilumbrales Hi again! Hope your holidays were great!

It's working perfectly. :-) Just update to `dev-master` and use the new classes `InstagramVideo` and `InstagramPhoto`. You can see them here:

https://github.com/mgp25/Instagram-API/blob/32f6c7289b052ff397bc6a5cea805f2139627652/examples/uploadPhoto.php#L42-L43

https://github.com/mgp25/Instagram-API/blob/32f6c7289b052ff397bc6a5cea805f2139627652/examples/uploadVideo.php#L42-L43

You can provide options to the classes, as before. Just check the class files :)

**Pull request closed without merging**
