### PR TITLE
Fix pre-login flow

### PR DESCRIPTION
**Pull request by valga**
This one is for @mgp25.

Basically there is nothing important here: I just replaced deprecated endpoint with new one, and tweaked a param for login experiments call.

### CODE REVIEW

**Comment by mgp25** [comment]
@valga its 100% correct!

**Comment by mgp25** [comment]
@valga is there any reason you changed it from protected to public?

**Comment by valga** [comment]
Strictly speaking, I did not change the visibility, but the diff looks like I did that. In reality I removed non-used protected method and added new public method.

I guess old method was protected, because it was related with sign up sequence (abused by spamers).

New method just registers an advertising ID, it has nothing to do with sign up. And as far as I remember, you can reset that ID on Android device, so I made it public.

**Comment by SteveJobzniak** [comment]
@valga Sounds good to me!

**Pull request merged**
