### PR TITLE
Fixing API headers

### PR DESCRIPTION
**Pull request by BaderMudarra**
Based on most recent version for android # 26.0.0.13.86
The following two headers are not being sent any longer, so I removed them.
* X-FB-HTTP-Engine
* Accept

Also, `Accept-Encoding` header is sent with `gzip` value instead of `gzip,deflate`

### CODE REVIEW

**Comment by aitte2** [comment]
https://github.com/mgp25/Instagram-API/blob/d28ab4803843310f32e328e6742c05ba55d16555/src/Constants.php#L12

**Comment by mgp25** [comment]
Yes, in the current version, headers still exist. When we add everything that is in that version, we'll merge this PR

Regards

**Comment by davisjackie321** [comment]
Yea

**Comment by aitte2** [comment]
@mgp25 hi. Isnt this PR needed  after https://github.com/mgp25/Instagram-API/commit/d0d289422b933d261c03e173d548434bd790bcb6 ? Or are the headers back to being the same again?

**Pull request closed without merging**
