### PR TITLE
Internal: check for audio stream

### PR DESCRIPTION
**Pull request by alexok**
ffmpeg wrapper throws an exception when loading video without audio stream

### CODE REVIEW

**Comment by aitte2** [comment]
@alexok Please describe why this change is necessary? I can guess why, and it seems fine if it does what I suspect, but please tell us. ;) 

And merging will need to wait until @valga has finished the ffmpeg wrapper rewrite (#1893).

**Comment by alexok** [comment]
@aitte2 I updated the description

**Comment by aitte2** [comment]
This change means no audio segment files are created, which is logical since no audio exists. So disabling splitting to audio makes sense.

But I just wonder if the later encoder/uploader code will look for those missing audio files and is broken by this change?

**Comment by alexok** [comment]
Ready

**Comment by aitte2** [comment]
@alexok Thanks a lot alex! 👍 :)

Question: Since you obviously tested this change, did the videos (without audio) upload correctly to Instagram after this change?

**Comment by alexok** [comment]
Yes, video without audio is loaded normally

**Comment by aitte2** [comment]
Thanks, perfect news :)

**Pull request merged**
