### PR TITLE
Realtime update

### PR DESCRIPTION
**Pull request by valga**
There is nothing new here: it is just a maintenance. See commits for changelog.

### CODE REVIEW

**Comment by SteveJobzniak** [comment]
Thank you so much, this is freaking awesome! I wonder about the 10.29.0 commit which removes websocket. Is it safe to merge this while our non-subscriber constants are at 10.22.0?

**Comment by SteveJobzniak** [comment]
Ehh, I'll merge it! If we find some problem with constants we can deal with it somehow.

**Comment by valga** [comment]
See #1353. Instagram doesn't have WebSocket server anymore.

**Comment by SteveJobzniak** [comment]
Ahh perfect! So it's safe. :)

By the way, you said you are waiting for some constant bump for a feature... which version is it you need?

We'll have to consider bumping soon, because Instagram Live Replays exist in all story feeds for newer clients, so we'll have to see what version to bump to.

**Comment by SteveJobzniak** [comment]
10.26 added Replays: https://hypebeast.com/2017/6/instagram-stories-replay-live-video

I think that was the exact version you were waiting for?

**Comment by valga** [comment]
Yeah, I mentioned 10.26.0 as a good candidate to bump to. And I confirm that it is needed to get `post_live` fields (aka live replays) in responses.

**Comment by SteveJobzniak** [comment]
@valga Okay so it's settled, I'll bump to 10.26.0 in a moment. Have you got any username I can test with to look for the post_live field and implement its model object? I can't find anybody who has saved a replay, but it sounds like you have someone.

**Comment by valga** [comment]
@SteveJobzniak jamieleesix. Also we need to update (login) experiments.

**Comment by mgp25** [comment]
@valga will update experiments and so tonight.

**Pull request merged**
