### PR TITLE
Zero rating rewrites implementation

### PR DESCRIPTION
**Pull request by valga**
It has been simplified: for example, the app stores multiple tokens (per carrier) and switches between them when you change your SIM card. As we don't have a mobile network, it is ok to keep just one token (that is always empty anyway).

@mgp25 Do not squash this PR: it meant to be in 2 individual commits. Do a rebase.

### CODE REVIEW

**Comment by aitte2** [comment]
Wow looks like a big job. Impressive! :)

I only have one feedback: Why are getters `$ig->client->zeroRewrite()->update()` instead of `$ig->client->getZeroRewrite()->update()`? The word `get` is missing from your new getters... which makes them look like "action" functions rather than getters.

Since there's no "get" word I read `$ig->client->zeroRewrite()` as "trigger a client zero-rewrite call"... 😮

**Comment by mgp25** [comment]
@valga let me know when this is ready to merge.

Regards

**Comment by valga** [comment]
@aitte2 I renamed it to `zeroRating()` to cause less confusion. There is no point in `get` prefix when we have no setter.

@mgp25 It's almost ready.

**Comment by valga** [comment]
@mgp25 It's ready.

**Pull request merged**
