### PR TITLE
Adding new 'tv_channel' property in Highlight::getUserFeed

### PR DESCRIPTION
**Pull request by Pezhvak**
there is a new property added to Highlight::getUserFeed response which is 'tv_channel', i added the new model and also updated Highlight request class.

### CODE REVIEW

**Comment by Pezhvak** [comment]
it's ready now, please review

**Comment by mgp25** [comment]
@Pezhvak have you run `composer codestyle` ? That will prepare the code according to out coding style

**Comment by Pezhvak** [comment]
ouh, i was wondering how you guys did it in the first place, awesome, i'm gonna use it now and commit changes now

**Comment by Pezhvak** [comment]
@mgp25 ouh, i was wondering how you guys did it in the first place, awesome, i'm gonna use it now and commit changes now

**Comment by Pezhvak** [comment]
@mgp25 ouh, i was wondering how you guys did it in the first place, awesome, i'm gonna use it now and commit changes

**Comment by Pezhvak** [comment]
wow, that was.. i really really enjoyed using that command. all that time i lost trying writing things manually  (－‸ლ)

**Comment by Pezhvak** [comment]
wow, that was.. i really really enjoyed using that command. all that time i lost trying to type things manually (－‸ლ)

**Comment by Pezhvak** [comment]
hey @JRoy, did you know about `composer codestyle`? yesterday we where trying to fix things manually (－‸ლ)

**Comment by JRoy** [comment]
I did lmao, it's sorta hit or miss on windows and I didn't know what operating system you have and I was busy and didn't want to explain it if you had windows :P

**Comment by JRoy** [comment]
I'm going to wait for @mgp25 to merge this because you changed a lot of files, so it's up to them.

**Comment by Pezhvak** [comment]
i'm using mac and my laptop is linux, don't like windows at all ^_^ sure m8. just to be clear i added 1 file (corresponding to the new tv_channel property) and changed two other files to respond and clarify, the rest is changed by the command, it seems it likes null to be after other types, any how. i will wait for @mgp25 to review this. thanks ^_^

**Pull request merged**
