### PR TITLE
fixed if/else statements for mysql settings and added new columns to create table query

### PR DESCRIPTION
**Pull request by zuexo**
'device_id', 'uuid' and 'phone_id' are now also stored when using mysql database.
I hope the size of VARCHAR is appropriate.

### CODE REVIEW

**Comment by SteveJobzniak** [comment]
Thanks, I'll review this later when I have time.

**Comment by SteveJobzniak** [comment]
Okay I've done a quick review now. Your huge "fixed" if/else statements do exactly the same thing as the original code. So I'll just manually update the database columns. Thanks for discovering that we forgot to add those.

**Comment by SteveJobzniak** [comment]
And fyi: VARCHAR in MySQL is variable-length on disk. The parenthesis just sets their max allowed length. So the appropriate value is 255, to be sure we'll fit any values.

Anyway, thanks again for beinging the database column issue to our attention. It has been fixed now.

https://github.com/mgp25/Instagram-API/commit/28b5d3d91e0e8db66a9847f9ca479e95a78a1e01

**Comment by zuexo** [comment]
The ternary operator does not support elseif without parenthesis. The bottom code should print config_table for all if it worked like that but it doesn't.
```php
<?php
putenv("DB_TABLENAME=env_table");
$config = ["tablename" => "config_table"];
$options = ["db_tablename" => "options_table"];
$env_tablename = getenv('DB_TABLENAME');

$dbTableName = array_key_exists('tablename', $config) ? $config['tablename'] : array_key_exists('db_tablename', $options) ? $options['db_tablename'] : $env_tablename !== false ? $env_tablename : null;
print_r($dbTableName."\n"); //prints env_table

$dbTableName = array_key_exists('tablename', $config) ? $config['tablename'] : (array_key_exists('db_tablename', $options) ? $options['db_tablename'] : ($env_tablename !== false ? $env_tablename : null));
print_r($dbTableName."\n"); //prints config_table

if (array_key_exists('tablename', $config)) {
    $dbTableName = $config['tablename'];
} elseif (array_key_exists('db_tablename', $options)) {
    $dbTableName = $options['db_tablename'];
} elseif ($env_tablename !== false) {
    $dbTableName = $env_tablename;
} else {
    $dbTableName = null;
}
 print_r($dbTableName."\n"); //prints config_table
```

**Comment by Lastwisher** [comment]
While we put effort to shorter and cleaner code, this is not a upgrade.

**Comment by SteveJobzniak** [comment]
Fixed properly in https://github.com/mgp25/Instagram-API/commit/3fb4516b8a5645921f4744e53fe214ee177d63f4.

**Pull request closed without merging**
