### PR TITLE
set_gender endpoint added

### PR DESCRIPTION
**Pull request by Pezhvak**
hey, as described in #2744, i've added the endpoint.

### CODE REVIEW

**Comment by JRoy** [comment]
Looks good so far but you forgot the warning to use the edit profile request: ```*WRNLNG: Remember to also call editProtile atter* us ing this Eunction. that you act Like the real app```

**Comment by Pezhvak** [comment]
done

**Comment by JRoy** [comment]
Looks good, will merge later

**Comment by Pezhvak** [comment]
alright, but i was looking into it, why is it required to call editProfile? i just looked at the traffic, it simply just calls the endpoint and you can go out of edit profile section. no other request is being sent in this process

**Comment by JRoy** [comment]
This may have changed after v85, when I do our next constants update and request audit, I will look into then. For now it's fine

**Comment by Pezhvak** [comment]
i'm going through the apis, i will keep you updated if i found other things (v100.0.0.17.129)

**Comment by JRoy** [comment]
Thanks for your contribution!

**Pull request merged**
