### PR TITLE
fix: set geolocation

### PR DESCRIPTION
**Pull request by skn2215**

### CODE REVIEW

**Comment by SteveJobzniak** [comment]
Thanks a lot. We'll have to verify this change, and we also need to change it in all the other code places that send locations.

Interestingly, the old code for adding locations on uploads was last tested by me a month or two ago and worked then. So perhaps they recently changed it.

**Comment by mgp25** [comment]
Verifying. Give me 5-10 minutes

**Comment by SteveJobzniak** [comment]
@mgp25 Great. My biggest concern is that I'm not sure that all locations have a FacebookPlacesId value. Non-Facebook based locations don't havr any, if I remember correctly.

**Comment by mgp25** [comment]
@SteveJobzniak gitter

**Comment by SteveJobzniak** [comment]
Okay, we've verified. This change is not completely correct and only fixes 1 of 4 code locations. We'll code the fix, but thank you very much for finding the problem!

**Comment by mgp25** [comment]
@skn2215 i have closed your PR, because the fix require multiple changes. We'll be adding it in the next couple minutes. 


Regards

**Comment by SteveJobzniak** [comment]
We found the real problem. I'll answer in your ticket: https://github.com/mgp25/Instagram-API/issues/1539

**Pull request closed without merging**
