### PR TITLE
Added new objects and props to classes

### PR DESCRIPTION
**Pull request by zuexo**
Added Broadcast object and few props to other objects.
Also added SuggestedUsers object

### CODE REVIEW

**Comment by SteveJobzniak** [comment]
@zuexo Thanks a lot for contributing all these new response objects! Some of them need typefixes but I'll take care of it after the current work.

For future reference:

Every ID (almost everything with "pk" or "id" in keyname): string, to avoid overflowing int/floats

Every lat & lng: float, for proper location precision.

**Comment by SteveJobzniak** [comment]
Here's how it was fixed:

https://github.com/mgp25/Instagram-API/commit/68c07cf22d300add8f037b7a6176486976d2be6b

Thanks again for running with the apiDeveloperDebug mode and finding all of these in the first place. It certainly helped a lot!

**Comment by zuexo** [comment]
My contribution is all thanks to you. You changed api debuging to be less complex.
And for the future I'll keep that in mind and not forget setting types in annotations.

**Comment by SteveJobzniak** [comment]
@zuexo Happy to hear that. And thank you very much. I'm really loving your contributions. :)

**Comment by SteveJobzniak** [comment]
@zuexo By the way, you should really fix your Git config. Everything you submit is being contributed as `Matej Mihevc <Matej Mihevc>` which means it cannot be clicked to lead to your GitHub profile.

Do `git config user.name zuexo` and `git config user.email zuexo@users.noreply.github.com` while in your local copy of our repo. :)

Or fix it globally on your whole machine by adding `git config --global` to those commands above.

**Comment by zuexo** [comment]
Thanks for the info. It probably broke when I started using Gitlab. :)
Will fix it right now!

**Comment by SteveJobzniak** [comment]
@zuexo We've been looking at your contributions. You've clearly got intelligence and a sense for quality code. We decided to invite you as a collaborator so that you can commit directly to the project with any other improvements you come up with. 👍

**Pull request merged**
