### PR TITLE
Models: Update MediaInsights

### PR DESCRIPTION
**Pull request by Bruellmuecke112**
While trying to get mediaInsights like ImpressionsCount or EngagementCount, I received a Response similar to the issue [2161](https://github.com/mgp25/Instagram-API/issues/2161).

Changing the file src/Response/MediaInsightsResponse.php similar to you commit fd035b3 fixed the problem for me.

Thx for your work!

### CODE REVIEW

**Comment by mgp25** [comment]
@Bruellmuecke112 could you post the response here?

**Comment by Bruellmuecke112** [comment]
Is it that what you want?

GET:  https://i.instagram.com/api/v1/insights/media_organic_insights/1888464020601191233/?ig_sig_key_version=4
→ 0B
← 200 	 195B
RESPONSE: {"media_organic_insights": {"like_count": 19, "comment_count": 0, "save_count": 0, "impression_count": 224, "reach_count": 191, "engagement_count": 19, "avg_engagement_count": 0}, "status": "ok"}

**Comment by mgp25** [comment]
@Bruellmuecke112 would you mind updating `Model\MediaInsights` too? With the missing attributes from the response and setting their correct typpe?

Regards

**Comment by mgp25** [comment]
Update in commit: https://github.com/mgp25/Instagram-API/commit/85dd77a3a5ac9cc99e345871c069cab516176c6a

Regards

**Pull request closed without merging**
