### PR TITLE
Add support of thumbnail in albums

### PR DESCRIPTION
**Pull request by e4se**
Added support of thumbnail in albums

### CODE REVIEW

**Comment by JRoy** [comment]
@e4se could you please include examples and have you tested this?

**Comment by mgp25** [comment]
Does Instagram allows setting your own thumbnail? Because if not, we shouldn't add this.

Regards

**Comment by JRoy** [comment]
@mgp25 I'm not familiar on how the thumbnail system works from an API standpoint but I know you can pick frames from the video in the app to set as the thumbnail (for post video and album posts)

**Comment by e4se** [comment]
Add example for this. Of cause I tested this feature and Instagram allows pick frames from the video to set as the thumbnail for every video in albums)

**Comment by JRoy** [comment]
Well if it works, it works. I know Instagram allows for this behavior and feature looks good to me. I'll wait for mgp's opinion before merge tho...

**Comment by mgp25** [comment]
If this works and album supports it, then perfect. There is a comment that you be removed:  `// NOTE: This is NOT for albums!` since now it also for albums

**Comment by e4se** [comment]
Remove outdated comment

**Comment by JRoy** [comment]
Thanks for your contribution!

**Pull request merged**
