### PR TITLE
Fix for story view count.

### PR DESCRIPTION
**Pull request by matthijsotterloo**
This fixes the view count for the getUserStoryFeed() function.

### CODE REVIEW

**Comment by mgp25** [comment]
@matthijsotterloo provide Instagram response to verify this + don't replace it, `view_count` is an attributte used by Instagram

**Comment by matthijsotterloo** [comment]
Can't get the response now, but tested and working.

**Comment by matthijsotterloo** [comment]
`[
   {
      "taken_at":1494864473,
      "pk":"1515355544074870891",
      "id":"1515355544074870891_5424478926",
      "device_timestamp":1494864473,
      "media_type":2,
      "code":"BUHn9axAGBr",
      "client_cache_key":"MTUxNTM1NTU0NDA3NDg3MDg5MQ==.2",
      "filter_type":0,
      "attribution":null,
      "image_versions2":{
         "candidates":[
            {
               "url":"http:\/\/scontent-amt2-1.cdninstagram.com\/t51.9792-15\/e15\/p640x640\/15387152_149153135623989_1913270650328317952_n.jpg?ig_cache_key=MTUxNTM1NTU0NDA3NDg3MDg5MQ%3D%3D.2",
               "width":640,
               "height":1137,
               "status":null,
               "message":null,
               "fullResponse":null
            },
            {
               "url":"http:\/\/scontent-amt2-1.cdninstagram.com\/t51.9792-15\/e15\/p240x240\/15387152_149153135623989_1913270650328317952_n.jpg?ig_cache_key=MTUxNTM1NTU0NDA3NDg3MDg5MQ%3D%3D.2",
               "width":240,
               "height":426,
               "status":null,
               "message":null,
               "fullResponse":null
            }
         ],
         "status":null,
         "message":null,
         "fullResponse":null
      },
      "original_width":720,
      "original_height":1280,
      "viewer_count":1,
      "organic_tracking_token":"eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwidXVpZCI6ImM3OGUzNzgxNDNiMjQxZGJhYzljMzkxZmNmM2FmMmZhMTUxNTM1NTU0NDA3NDg3MDg5MSIsInNlcnZlcl90b2tlbiI6IjE0OTQ5NDA3Mzg0NTZ8MTUxNTM1NTU0NDA3NDg3MDg5MXw1NDI0NDc4OTI2fGJhYmRlYjA5Njg4MTBmNjExNmE3YzBjNTY3ZjU4OTNiYzAyMzE2OTJiOTIwMTExZWZjMDVhYzFlZDc1YWI3ZDEifSwic2lnbmF0dXJlIjoiIn0=",
      "has_more_comments":false,
      "max_num_visible_preview_comments":4,
      "preview_comments":[

      ],
      "comments_disabled":null,
      "reel_mentions":[

      ],
      "story_cta":null,
      "caption_position":0,
      "expiring_at":1494950873,
      "is_reel_media":true,
      "next_max_id":null,
      "carousel_media":null,
      "comments":null,
      "comment_count":0,
      "caption":null,
      "caption_is_edited":false,
      "photo_of_you":false,
      "video_versions":[
         {
            "url":"http:\/\/scontent-amt2-1.cdninstagram.com\/t50.9793-16\/15265750_183108098879312_2808267789578534912_n.mp4",
            "type":101,
            "width":640,
            "height":1137,
            "status":null,
            "message":null,
            "fullResponse":null
         },
         {
            "url":"http:\/\/scontent-amt2-1.cdninstagram.com\/t50.9793-16\/16777691_1925140577761405_2337090176192348160_n.mp4",
            "type":103,
            "width":480,
            "height":853,
            "status":null,
            "message":null,
            "fullResponse":null
         },
         {
            "url":"http:\/\/scontent-amt2-1.cdninstagram.com\/t50.9793-16\/16777691_1925140577761405_2337090176192348160_n.mp4",
            "type":102,
            "width":480,
            "height":853,
            "status":null,
            "message":null,
            "fullResponse":null
         }
      ],
      "has_audio":false,
      "video_duration":5.70000000000000017763568394002504646778106689453125,
      "user":{
         "username":"snapboardnl",
         "has_anonymous_profile_picture":false,
         "is_favorite":null,
         "profile_pic_url":"http:\/\/scontent-amt2-1.cdninstagram.com\/t51.2885-19\/s150x150\/18382137_456161448064040_7344335819223597056_a.jpg",
         "full_name":"SnapBoard",
         "pk":"5424478926",
         "is_verified":false,
         "is_private":false,
         "coeff_weight":null,
         "friendship_status":null,
         "hd_profile_pic_versions":null,
         "byline":null,
         "search_social_context":null,
         "unseen_count":null,
         "mutual_followers_count":null,
         "follower_count":null,
         "social_context":null,
         "media_count":null,
         "following_count":null,
         "is_business":null,
         "usertags_count":null,
         "profile_context":null,
         "biography":null,
         "geo_media_count":null,
         "is_unpublished":false,
         "allow_contacts_sync":null,
         "show_feed_biz_conversion_icon":null,
         "profile_pic_id":"1514624064629763209_5424478926",
         "auto_expand_chaining":null,
         "can_boost_post":false,
         "is_profile_action_needed":null,
         "has_chaining":null,
         "include_direct_blacklist_status":null,
         "can_see_organic_insights":false,
         "can_convert_to_business":null,
         "convert_from_pages":null,
         "show_business_conversion_icon":null,
         "show_conversion_edit_entry":null,
         "show_insights_terms":false,
         "can_create_sponsor_tags":null,
         "hd_profile_pic_url_info":null,
         "usertag_review_enabled":null,
         "profile_context_mutual_follow_ids":null,
         "profile_context_links_with_user_ids":null,
         "has_biography_translation":null,
         "business_contact_method":null,
         "category":null,
         "direct_messaging":null,
         "fb_page_call_to_action_id":null,
         "is_call_to_action_enabled":null,
         "public_phone_country_code":null,
         "public_phone_number":null,
         "contact_phone_number":null,
         "latitude":null,
         "longitude":null,
         "address_street":null,
         "zip":null,
         "city_id":null,
         "city_name":null,
         "public_email":null,
         "is_needy":null,
         "external_url":null,
         "external_lynx_url":null,
         "email":null,
         "country_code":null,
         "birthday":null,
         "national_number":null,
         "gender":null,
         "phone_number":null,
         "needs_email_confirm":null,
         "status":null,
         "message":null,
         "fullResponse":null
      },
      "likers":[

      ],
      "like_count":0,
      "preview":null,
      "has_liked":false,
      "explore_context":null,
      "explore_source_token":null,
      "explore":null,
      "impression_token":null,
      "usertags":null,
      "media_or_ad":null,
      "media":null,
      "stories":null,
      "top_likers":null,
      "suggested_users":null,
      "comment_likes_enabled":false,
      "can_viewer_save":true,
      "has_viewer_saved":null,
      "location":null,
      "lat":null,
      "lng":null,
      "story_locations":[

      ],
      "algorithm":null,
      "status":null,
      "message":null,
      "fullResponse":null
   },
   {
      "taken_at":1494865070,
      "pk":"1515360561368558919",
      "id":"1515360561368558919_5424478926",
      "device_timestamp":1494865069951,
      "media_type":1,
      "code":"BUHpGbfAm1H",
      "client_cache_key":"MTUxNTM2MDU2MTM2ODU1ODkxOQ==.2",
      "filter_type":0,
      "attribution":null,
      "image_versions2":{
         "candidates":[
            {
               "url":"http:\/\/scontent-amt2-1.cdninstagram.com\/t51.9792-15\/e35\/18559675_303629336758593_988651186062098432_n.jpg?ig_cache_key=MTUxNTM2MDU2MTM2ODU1ODkxOQ%3D%3D.2&se=7",
               "width":1080,
               "height":1350,
               "status":null,
               "message":null,
               "fullResponse":null
            },
            {
               "url":"http:\/\/scontent-amt2-1.cdninstagram.com\/t51.9792-15\/e35\/p240x240\/18559675_303629336758593_988651186062098432_n.jpg?ig_cache_key=MTUxNTM2MDU2MTM2ODU1ODkxOQ%3D%3D.2",
               "width":240,
               "height":300,
               "status":null,
               "message":null,
               "fullResponse":null
            }
         ],
         "status":null,
         "message":null,
         "fullResponse":null
      },
      "original_width":1080,
      "original_height":1350,
      "viewer_count":1,
      "organic_tracking_token":"eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwidXVpZCI6ImM3OGUzNzgxNDNiMjQxZGJhYzljMzkxZmNmM2FmMmZhMTUxNTM2MDU2MTM2ODU1ODkxOSIsInNlcnZlcl90b2tlbiI6IjE0OTQ5NDA3Mzg0NTZ8MTUxNTM2MDU2MTM2ODU1ODkxOXw1NDI0NDc4OTI2fGM0YjJjMzZmNTM5ZTYwZTdhMzgxNjM5YjA5MTJhMWYyMmQ1NTg5ZDQ5YTk1ZjZmMThhZmVlYTA3NWU0YzNhOGEifSwic2lnbmF0dXJlIjoiIn0=",
      "has_more_comments":false,
      "max_num_visible_preview_comments":4,
      "preview_comments":[

      ],
      "comments_disabled":null,
      "reel_mentions":[

      ],
      "story_cta":null,
      "caption_position":0,
      "expiring_at":1494951470,
      "is_reel_media":true,
      "next_max_id":null,
      "carousel_media":null,
      "comments":null,
      "comment_count":0,
      "caption":null,
      "caption_is_edited":false,
      "photo_of_you":false,
      "video_versions":null,
      "has_audio":null,
      "video_duration":null,
      "user":{
         "username":"snapboardnl",
         "has_anonymous_profile_picture":false,
         "is_favorite":null,
         "profile_pic_url":"http:\/\/scontent-amt2-1.cdninstagram.com\/t51.2885-19\/s150x150\/18382137_456161448064040_7344335819223597056_a.jpg",
         "full_name":"SnapBoard",
         "pk":"5424478926",
         "is_verified":false,
         "is_private":false,
         "coeff_weight":null,
         "friendship_status":null,
         "hd_profile_pic_versions":null,
         "byline":null,
         "search_social_context":null,
         "unseen_count":null,
         "mutual_followers_count":null,
         "follower_count":null,
         "social_context":null,
         "media_count":null,
         "following_count":null,
         "is_business":null,
         "usertags_count":null,
         "profile_context":null,
         "biography":null,
         "geo_media_count":null,
         "is_unpublished":false,
         "allow_contacts_sync":null,
         "show_feed_biz_conversion_icon":null,
         "profile_pic_id":"1514624064629763209_5424478926",
         "auto_expand_chaining":null,
         "can_boost_post":false,
         "is_profile_action_needed":null,
         "has_chaining":null,
         "include_direct_blacklist_status":null,
         "can_see_organic_insights":false,
         "can_convert_to_business":null,
         "convert_from_pages":null,
         "show_business_conversion_icon":null,
         "show_conversion_edit_entry":null,
         "show_insights_terms":false,
         "can_create_sponsor_tags":null,
         "hd_profile_pic_url_info":null,
         "usertag_review_enabled":null,
         "profile_context_mutual_follow_ids":null,
         "profile_context_links_with_user_ids":null,
         "has_biography_translation":null,
         "business_contact_method":null,
         "category":null,
         "direct_messaging":null,
         "fb_page_call_to_action_id":null,
         "is_call_to_action_enabled":null,
         "public_phone_country_code":null,
         "public_phone_number":null,
         "contact_phone_number":null,
         "latitude":null,
         "longitude":null,
         "address_street":null,
         "zip":null,
         "city_id":null,
         "city_name":null,
         "public_email":null,
         "is_needy":null,
         "external_url":null,
         "external_lynx_url":null,
         "email":null,
         "country_code":null,
         "birthday":null,
         "national_number":null,
         "gender":null,
         "phone_number":null,
         "needs_email_confirm":null,
         "status":null,
         "message":null,
         "fullResponse":null
      },
      "likers":[

      ],
      "like_count":0,
      "preview":null,
      "has_liked":false,
      "explore_context":null,
      "explore_source_token":null,
      "explore":null,
      "impression_token":null,
      "usertags":null,
      "media_or_ad":null,
      "media":null,
      "stories":null,
      "top_likers":null,
      "suggested_users":null,
      "comment_likes_enabled":false,
      "can_viewer_save":true,
      "has_viewer_saved":null,
      "location":null,
      "lat":null,
      "lng":null,
      "story_locations":[

      ],
      "algorithm":null,
      "status":null,
      "message":null,
      "fullResponse":null
   },
   {
      "taken_at":1494939152,
      "pk":"1515982007946065683",
      "id":"1515982007946065683_5424478926",
      "device_timestamp":1494939152437,
      "media_type":1,
      "code":"BUJ2ZqtgjcT",
      "client_cache_key":"MTUxNTk4MjAwNzk0NjA2NTY4Mw==.2",
      "filter_type":0,
      "attribution":null,
      "image_versions2":{
         "candidates":[
            {
               "url":"http:\/\/scontent-amt2-1.cdninstagram.com\/t51.9792-15\/e35\/14084557_331086050643769_44842035550617600_n.jpg?ig_cache_key=MTUxNTk4MjAwNzk0NjA2NTY4Mw%3D%3D.2&se=7",
               "width":1080,
               "height":1350,
               "status":null,
               "message":null,
               "fullResponse":null
            },
            {
               "url":"http:\/\/scontent-amt2-1.cdninstagram.com\/t51.9792-15\/e35\/p240x240\/14084557_331086050643769_44842035550617600_n.jpg?ig_cache_key=MTUxNTk4MjAwNzk0NjA2NTY4Mw%3D%3D.2",
               "width":240,
               "height":300,
               "status":null,
               "message":null,
               "fullResponse":null
            }
         ],
         "status":null,
         "message":null,
         "fullResponse":null
      },
      "original_width":1080,
      "original_height":1350,
      "viewer_count":1,
      "organic_tracking_token":"eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwidXVpZCI6ImM3OGUzNzgxNDNiMjQxZGJhYzljMzkxZmNmM2FmMmZhMTUxNTk4MjAwNzk0NjA2NTY4MyIsInNlcnZlcl90b2tlbiI6IjE0OTQ5NDA3Mzg0NTV8MTUxNTk4MjAwNzk0NjA2NTY4M3w1NDI0NDc4OTI2fGE4ZTMyM2I5ZWRmYmEwODgzZjJhYWI3MTZmYmMyZTg4YjlhMmZlOThlYzY0YzQzZjA0NGNlMjJjNWMwZjBmYzAifSwic2lnbmF0dXJlIjoiIn0=",
      "has_more_comments":false,
      "max_num_visible_preview_comments":4,
      "preview_comments":[

      ],
      "comments_disabled":null,
      "reel_mentions":[

      ],
      "story_cta":null,
      "caption_position":0,
      "expiring_at":1495025552,
      "is_reel_media":true,
      "next_max_id":null,
      "carousel_media":null,
      "comments":null,
      "comment_count":0,
      "caption":null,
      "caption_is_edited":false,
      "photo_of_you":false,
      "video_versions":null,
      "has_audio":null,
      "video_duration":null,
      "user":{
         "username":"snapboardnl",
         "has_anonymous_profile_picture":false,
         "is_favorite":null,
         "profile_pic_url":"http:\/\/scontent-amt2-1.cdninstagram.com\/t51.2885-19\/s150x150\/18382137_456161448064040_7344335819223597056_a.jpg",
         "full_name":"SnapBoard",
         "pk":"5424478926",
         "is_verified":false,
         "is_private":false,
         "coeff_weight":null,
         "friendship_status":null,
         "hd_profile_pic_versions":null,
         "byline":null,
         "search_social_context":null,
         "unseen_count":null,
         "mutual_followers_count":null,
         "follower_count":null,
         "social_context":null,
         "media_count":null,
         "following_count":null,
         "is_business":null,
         "usertags_count":null,
         "profile_context":null,
         "biography":null,
         "geo_media_count":null,
         "is_unpublished":false,
         "allow_contacts_sync":null,
         "show_feed_biz_conversion_icon":null,
         "profile_pic_id":"1514624064629763209_5424478926",
         "auto_expand_chaining":null,
         "can_boost_post":false,
         "is_profile_action_needed":null,
         "has_chaining":null,
         "include_direct_blacklist_status":null,
         "can_see_organic_insights":false,
         "can_convert_to_business":null,
         "convert_from_pages":null,
         "show_business_conversion_icon":null,
         "show_conversion_edit_entry":null,
         "show_insights_terms":false,
         "can_create_sponsor_tags":null,
         "hd_profile_pic_url_info":null,
         "usertag_review_enabled":null,
         "profile_context_mutual_follow_ids":null,
         "profile_context_links_with_user_ids":null,
         "has_biography_translation":null,
         "business_contact_method":null,
         "category":null,
         "direct_messaging":null,
         "fb_page_call_to_action_id":null,
         "is_call_to_action_enabled":null,
         "public_phone_country_code":null,
         "public_phone_number":null,
         "contact_phone_number":null,
         "latitude":null,
         "longitude":null,
         "address_street":null,
         "zip":null,
         "city_id":null,
         "city_name":null,
         "public_email":null,
         "is_needy":null,
         "external_url":null,
         "external_lynx_url":null,
         "email":null,
         "country_code":null,
         "birthday":null,
         "national_number":null,
         "gender":null,
         "phone_number":null,
         "needs_email_confirm":null,
         "status":null,
         "message":null,
         "fullResponse":null
      },
      "likers":[

      ],
      "like_count":0,
      "preview":null,
      "has_liked":false,
      "explore_context":null,
      "explore_source_token":null,
      "explore":null,
      "impression_token":null,
      "usertags":null,
      "media_or_ad":null,
      "media":null,
      "stories":null,
      "top_likers":null,
      "suggested_users":null,
      "comment_likes_enabled":false,
      "can_viewer_save":true,
      "has_viewer_saved":null,
      "location":null,
      "lat":null,
      "lng":null,
      "story_locations":[

      ],
      "algorithm":null,
      "status":null,
      "message":null,
      "fullResponse":null
   }
]`

Response from Instagram.

**Comment by matthijsotterloo** [comment]
`[
   {
      "taken_at":1494864473,
      "pk":"1515355544074870891",
      "id":"1515355544074870891_5424478926",
      "device_timestamp":1494864473,
      "media_type":2,
      "code":"BUHn9axAGBr",
      "client_cache_key":"MTUxNTM1NTU0NDA3NDg3MDg5MQ==.2",
      "filter_type":0,
      "attribution":null,
      "image_versions2":{
         "candidates":[
            {
               "url":"http:\/\/scontent-amt2-1.cdninstagram.com\/t51.9792-15\/e15\/p640x640\/15387152_149153135623989_1913270650328317952_n.jpg?ig_cache_key=MTUxNTM1NTU0NDA3NDg3MDg5MQ%3D%3D.2",
               "width":640,
               "height":1137,
               "status":null,
               "message":null,
               "fullResponse":null
            },
            {
               "url":"http:\/\/scontent-amt2-1.cdninstagram.com\/t51.9792-15\/e15\/p240x240\/15387152_149153135623989_1913270650328317952_n.jpg?ig_cache_key=MTUxNTM1NTU0NDA3NDg3MDg5MQ%3D%3D.2",
               "width":240,
               "height":426,
               "status":null,
               "message":null,
               "fullResponse":null
            }
         ],
         "status":null,
         "message":null,
         "fullResponse":null
      },
      "original_width":720,
      "original_height":1280,
      "viewer_count":1,
      "organic_tracking_token":"eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjpmYWxzZSwidXVpZCI6ImM3OGUzNzgxNDNiMjQxZGJhYzljMzkxZmNmM2FmMmZhMTUxNTM1NTU0NDA3NDg3MDg5MSIsInNlcnZlcl90b2tlbiI6IjE0OTQ5NDA3Mzg0NTZ8MTUxNTM1NTU0NDA3NDg3MDg5MXw1NDI0NDc4OTI2fGJhYmRlYjA5Njg4MTBmNjExNmE3YzBjNTY3ZjU4OTNiYzAyMzE2OTJiOTIwMTExZWZjMDVhYzFlZDc1YWI3ZDEifSwic2lnbmF0dXJlIjoiIn0=",
      "has_more_comments":false,
      "max_num_visible_preview_comments":4,
      "preview_comments":[

      ],
      "comments_disabled":null,
      "reel_mentions":[

      ],
      "story_cta":null,
      "caption_position":0,
      "expiring_at":1494950873,
      "is_reel_media":true,
      "next_max_id":null,
      "carousel_media":null,
      "comments":null,
      "comment_count":0,
      "caption":null,
      "caption_is_edited":false,
      "photo_of_you":false,
      "video_versions":[
         {
            "url":"http:\/\/scontent-amt2-1.cdninstagram.com\/t50.9793-16\/15265750_183108098879312_2808267789578534912_n.mp4",
            "type":101,
            "width":640,
            "height":1137,
            "status":null,
            "message":null,
            "fullResponse":null
         },
         {
            "url":"http:\/\/scontent-amt2-1.cdninstagram.com\/t50.9793-16\/16777691_1925140577761405_2337090176192348160_n.mp4",
            "type":103,
            "width":480,
            "height":853,
            "status":null,
            "message":null,
            "fullResponse":null
         },
         {
            "url":"http:\/\/scontent-amt2-1.cdninstagram.com\/t50.9793-16\/16777691_1925140577761405_2337090176192348160_n.mp4",
            "type":102,
            "width":480,
            "height":853,
            "status":null,
            "message":null,
            "fullResponse":null
         }
      ],
      "has_audio":false,
      "video_duration":5.70000000000000017763568394002504646778106689453125,
      "user":{
         "username":"snapboardnl",
         "has_anonymous_profile_picture":false,
         "is_favorite":null,
         "profile_pic_url":"http:\/\/scontent-amt2-1.cdninstagram.com\/t51.2885-19\/s150x150\/18382137_456161448064040_7344335819223597056_a.jpg",
         "full_name":"SnapBoard",
         "pk":"5424478926",
         "is_verified":false,
         "is_private":false,
         "coeff_weight":null,
         "friendship_status":null,
         "hd_profile_pic_versions":null,
         "byline":null,
         "search_social_context":null,
         "unseen_count":null,
         "mutual_followers_count":null,
         "follower_count":null,
         "social_context":null,
         "media_count":null,
         "following_count":null,
         "is_business":null,
         "usertags_count":null,
         "profile_context":null,
         "biography":null,
         "geo_media_count":null,
         "is_unpublished":false,
         "allow_contacts_sync":null,
         "show_feed_biz_conversion_icon":null,
         "profile_pic_id":"1514624064629763209_5424478926",
         "auto_expand_chaining":null,
         "can_boost_post":false,
         "is_profile_action_needed":null,
         "has_chaining":null,
         "include_direct_blacklist_status":null,
         "can_see_organic_insights":false,
         "can_convert_to_business":null,
         "convert_from_pages":null,
         "show_business_conversion_icon":null,
         "show_conversion_edit_entry":null,
         "show_insights_terms":false,
         "can_create_sponsor_tags":null,
         "hd_profile_pic_url_info":null,
         "usertag_review_enabled":null,
         "profile_context_mutual_follow_ids":null,
         "profile_context_links_with_user_ids":null,
         "has_biography_translation":null,
         "business_contact_method":null,
         "category":null,
         "direct_messaging":null,
         "fb_page_call_to_action_id":null,
         "is_call_to_action_enabled":null,
         "public_phone_country_code":null,
         "public_phone_number":null,
         "contact_phone_number":null,
         "latitude":null,
         "longitude":null,
         "address_street":null,
         "zip":null,
         "city_id":null,
         "city_name":null,
         "public_email":null,
         "is_needy":null,
         "external_url":null,
         "external_lynx_url":null,
         "email":null,
         "country_code":null,
         "birthday":null,
         "national_number":null,
         "gender":null,
         "phone_number":null,
         "needs_email_confirm":null,
         "status":null,
         "message":null,
         "fullResponse":null
      },
      "likers":[

      ],
      "like_count":0,
      "preview":null,
      "has_liked":false,
      "explore_context":null,
      "explore_source_token":null,
      "explore":null,
      "impression_token":null,
      "usertags":null,
      "media_or_ad":null,
      "media":null,
      "stories":null,
      "top_likers":null,
      "suggested_users":null,
      "comment_likes_enabled":false,
      "can_viewer_save":true,
      "has_viewer_saved":null,
      "location":null,
      "lat":null,
      "lng":null,
      "story_locations":[

      ],
      "algorithm":null,
      "status":null,
      "message":null,
      "fullResponse":null
   },
]`

**Comment by matthijsotterloo** [comment]
@mgp25 API Response above. Changed as requested.

**Comment by mgp25** [comment]
👍  seems everything okay!

Thanks!

**Comment by SteveJobzniak** [comment]
@matthijsotterloo Thanks, so I see that the $debug=true suggestion worked well. ;-)

Fyi, since we re-use objects for many types of similar responses, Instagram may call something a view_count in one API and viewer_count in another, so that's why we don't delete old values.

We do have many old values that are no longer used by Instagram since they change things a bit over the years, but it was safer to keep everything and avoid breaking old code. We cannot go and check the ~100s of API endpoints to check what fields they all use. That would require a massive effort and the responses all vary based on the parameters too etc, so we simply don't delete any old fields unless we are 100% sure it's gone forever.

Anyway with that explanation out of the way, thanks a lot for researching and finding the answer to your own ticket. Excellent! :)

**Comment by matthijsotterloo** [comment]
@SteveJobzniak Yes that was indeed the solution! Okay, all clear. I understand and I'll keep this in mind for my next pull request ;)

**Comment by SteveJobzniak** [comment]
@matthijsotterloo Thanks. Glad it all worked out. Take care, good luck and have fun! :)

**Comment by luisfavila** [comment]
Hi there! I was trying to get viewer_count from getUserStoryFeed but it doesn't look to be sent by the server anymore. Does anyone have any update on this?

**Pull request merged**
