### PR TITLE
Add Question Sticker Support

### PR DESCRIPTION
**Pull request by JRoy**
This pull request adds the ability to answer a question sticker as well as updates the Item model to support viewing question sticker responses (as well as fetch their ids).

The new endpoint has been fully tested and works as expected.

Examples:
```php
$storyId = "1977230768527962393";
$questionId = "18036081463043385";
$ig->story->answerStoryQuestion($storyId, $questionId, "Hello World!")
```

### CODE REVIEW

**Comment by mgp25** [comment]
Everything seems okay. Does it returns a `GenericResponse`?

**Comment by JRoy** [comment]
@mgp25 yep, doesn't return anything special

**Comment by JRoy** [comment]
Merging due to no objections

**Comment by mgp25** [comment]
@JRoy 👍

**Pull request merged**
