### PR TITLE
Direct: Fix story recipients

### LINKED ISSUE #1438: sendDisappearingPhoto doesn't seem to work.
Hey,

Not sure if this is a known issue or not, but I was having some trouble with one of the endpoints related to "direct". Just a heads up before the release of 3.*.

When using the method `direct->sendDisappearingPhoto()`  it doesn't seem to be able to configure the uploaded image. Even when tried with different accounts.

Source Code:
```
<?php
require __DIR__.'/vendor/autoload.php';

/////// CONFIG ///////
$username = 'redacted';
$password = 'redacted';
$debug = true;
$truncatedDebug = false;
//////////////////////
/////// MEDIA ////////
$photoFilename = 'image.jpg';
$recipients= ["users" => ["1686677107"]];
//////////////////////


$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
try {
    $ig->setUser($username, $password);
    $ig->login();
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}
try {
    $ig->direct->sendDisappearingPhoto($recipients, $photoFilename);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}
```

Log files:

> POST: https://i.instagram.com/api/v1/upload/photo/ → 42.88kB ← 200 46B

> RESPONSE: {"upload_id": "1501194889721", "status": "ok"}
-----------
> POST: https://i.instagram.com/api/v1/media/configure_to_story/ DATA: signed_body=1c3f4accda568aaaeaad2b1da628a8ccbef2a6baa426f18863b3986c80f633b7.{"recipient_users":"[[\"1686677107\"]]","device":{"manufacturer":"ZTE","model":"ZTE A2017U","android_version":"23","android_release":"6.0.1"},"thread_ids":"[\"0\"]","_csrftoken":"T9R2qRfHVAtgx71qqhPzgj7fQD9pI9As","client_shared_at":"1501194890","configure_mode":"2","source_type":"3","_uid":"3232737714","_uuid":"8bb303c9-499b-45fc-ba31-b9fc0199cc91","edits":{"crop_original_size":[512,512],"crop_zoom":1,"crop_center":[0,-0]},"extra":{"source_width":512,"source_height":512},"upload_id":"1501194889721","client_timestamp":"1501194887"}&ig_sig_key_version=4 ← 500 75B 

>RESPONSE: {"message": "Other media configure error: b'FvpYh0sebg'", "status": "fail"}

Formated:
```
{  
   "recipient_users":"[[\"1686677107\"]]",
   "device":{  
      "manufacturer":"ZTE",
      "model":"ZTE A2017U",
      "android_version":"23",
      "android_release":"6.0.1"
   },
   "thread_ids":"[\"0\"]",
   "_csrftoken":"T9R2qRfHVAtgx71qqhPzgj7fQD9pI9As",
   "client_shared_at":"1501194890",
   "configure_mode":"2",
   "source_type":"3",
   "_uid":"3232737714",
   "_uuid":"8bb303c9-499b-45fc-ba31-b9fc0199cc91",
   "edits":{  
      "crop_original_size":[  
         512,
         512
      ],
      "crop_zoom":1,
      "crop_center":[  
         0,
         -0
      ]
   },
   "extra":{  
      "source_width":512,
      "source_height":512
   },
   "upload_id":"1501194889721",
   "client_timestamp":"1501194887"
}
```

------

The image that was used was a square 512x512:

### PR DESCRIPTION
**Pull request by valga**
Fixes #1438.

### CODE REVIEW

**Comment by mgp25** [comment]
@valga seems okay but in `Request/Direct` you forgot to remove `$useQuotes` from the arguments and doc, rest is okay.

Regards

**Comment by SteveJobzniak** [comment]
@valga Oh, this was a sneaky problem. Great discovery!

I'll echo what mgp25 said though: Is there any purpose for `$useQuotes` anymore? If not, it should be removed from everything that calls `_prepareRecipients` and from the arguments and docs.

**Comment by valga** [comment]
`$useQuotes` is still being used for thread IDs, because Instagram is inconsistent here: we should quote them for direct stories, but direct messages do not require quotes.

Also, while double checking quotes, I found an error with direct message params, so I included it in this PR.

**Comment by SteveJobzniak** [comment]
Oh, yeah I see that now. I didn't check deeply for $useQuotes since I read mgp25's message and assumed it really was orphaned.

Great, now merged. Thank you so much, this will surely make Direct users happy!

**Pull request merged**
