### PR TITLE
Push notifications (FBNS-based)

### PR DESCRIPTION
**Pull request by valga**
You are now able to receive pushes just like the app. See `examples/pushReceiver.php` for a basic receiver example.

### CODE REVIEW

**Comment by mgp25** [comment]
@valga i saw your comment, i know. Havent had time to change it. Also check this: https://github.com/mgp25/Instagram-API/commit/4f347830ade10a675966f48c4f615a4e5bf034ae#commitcomment-23475883

**Comment by valga** [comment]
@mgp25 I changed it in order to receive notifications. By the way, the example script works, so you can already receive pushes. There is just some technical stuff left, such as proxies, persistence and so on.

**Comment by mgp25** [comment]
@valga that are great news! Great work! I dont know if you have gitter, but if you want to share thought, code or whatever we can do it over there.

**Comment by valga** [comment]
@mgp25 I don't use IMs, so you can always reach me via email.

**Comment by valga** [comment]
Ok, it is ready for tests and review.

Don't forget to squash all commits into one when doing merge.

**Comment by mgp25** [comment]
I'll finish review tomorrow and do a couple of tests.

Great job 👍 😄

**Comment by mgp25** [comment]
@valga so far everything seems working fine and seems good to me. Is everything okay at your side?

**Comment by valga** [comment]
@mgp25 Just one thing. I documented only 3 types of pushes (with their params). And app has about 10-20 of them. What should we do?

**Comment by aitte2** [comment]
This is so cool. I just get nervous about your private fbns library in composer.json since evil code could be added to it later and composer would install that updated code. Please don't suddenly be evil in the future lol.

**Comment by mgp25** [comment]
@aitte2 i can tell you that @valga is a cool guy, you can trust him.

@valga send me the other types and ill write documentation about it, im writing full documentation of the API for release 3.0

Regards :)

**Comment by valga** [comment]
@aitte2 Well, you should be paranoid about other non-popular packages as well, so it multiplies your paranoia level by 4.

@mgp25 App doesn't have a list. It uses collapse key to group messages by it. So basically we have to receive and inspect all kinds of pushes. Or just leave it for users.

**Comment by mgp25** [comment]
@valga now i remember that i did this [/extradocs/Push_setPreferences.txt](https://github.com/mgp25/Instagram-API/blob/master/extradocs/Push_setPreferences.txt)

And yes, i agree with you, any extra information will be added as users discovers them.

**Comment by SteveJobzniak** [comment]
Hi all. Thanks a lot for this incredibly cool feature. The code seems clean as always. I don't have enough health available for a deep review.

So when it is ready, @mgp25, just merge it without me, and be sure to press "Squash and merge" so it gets squashed to a single commit.

**Comment by valga** [comment]
Well, pushes are ready to merge with that memory leak fix.

Realtime doesn't have memory leaks because it doesn't reuse MQTT client when doing a reconnect. But it is not nice (I mean we should reuse existing instance instead of creating a new one), so I will file a new PR after fixing `binsoul/net-mqtt-client-react` first.

**Comment by SteveJobzniak** [comment]
@valga Brilliant! ❤️ ❤️ 

Merged! I'll see you all around again when I feel better.

**Comment by crouchingtiger** [comment]
@valga Thanks for the effort on this, I was working on this separately for an Obj-C project. I was scratching my head for a while before realising they're utilising TCompactProtocol and not TBinaryProtocol (which re-maps some of the data types around). Despite getting things working, I only receive pushes (in my library and in yours) for the following push types over FBNS so far:

- New comments (``comment``)
- New user tags (``usertag``)
- New mentions (``mentioned_comment``)
- New messages (``direct_v2_message``)
- New followers (``new_follower``, sent only once, which makes sense if you try to spam someone follow/unfollow requests)

Some are a little harder to test as they're sporadic or require actions from Instagram (or some other remote job to run) eg. ``announcements``, ``notification_reminders``, ``contact_joined``, ``ads``, ``report_updated`` (when reporting users as spam). I'm also not getting ``liked`` notifications at all (not even to mobile devices).

Have you worked out a definitive list of which push types are received over GCM and which go over FBNS, or do they all go out over FBNS and there's perhaps some issue with my test accounts?

**Comment by valga** [comment]
@crouchingtiger Have you had `like` push notifications disabled in profile settings (I mean your edit)?

Nope, I did not collect all possible values, as I said in comments earlier. Do you mind filing a PR with them or at least providing captured pushes (I am interested in collapseKey and igAction)?

**Comment by crouchingtiger** [comment]
@valga I believe the issue was either because I'd like the post in the past (then un-liked it), or that I had disabled push (sending the ``push_disabled`` param on specific endpoints) at some point in the past. I was having trouble receiving all kinds of push types even though they were set to "All" or "Everyone", but it's working fine now. 

I'm going to document the push payloads again, but the ``collapse_key`` values are the ones I've posted above (these are different to the push preference keys).

**Comment by pesar368** [comment]
hi guys
i want use this feature in C# Instagram Api.
what i found is that i'm should conneting to 'mqtt-mini.facebook.com' with port 443
but Instagram mqtt need some other data 
like app key , Token , ... 

what is these Data ?

**Comment by valga** [comment]
@pesar368 
1. You have to patch your MQTT client, because Facebook uses non-standard protocol implementation. In short, you have to send `CONNECT` with Thrift payload and to receive `CONNACK` with JSON payload.
2. First connection to FBNS doesn't require any credentials, because the server will respond with the credentials you have to use in future connections.
3. Once you have established connection with a broker, you have to register your app to obtain Push token.
4. Then register obtained Push token with your user and listen for incoming Push notifications.

This flow is identical for all Facebook-powered apps, moreover you can share single FBNS connection between different apps.

Below are some useful links:
https://github.com/valga/fbns-react - It is the package with FBNS client.
https://github.com/binsoul/net-mqtt-client-react/pull/8#issuecomment-323951152 - A set of differences between standard MQTT protocol and FBNS one.
https://gist.github.com/valga/04e9028d21aa93b50e0768c0f39299e9 - A definition for Thrift structure used in `CONNECT` packet.
https://github.com/mgp25/Instagram-API/blob/master/src/Push.php - A wrapper for FBNS client to use it with the Instagram app.
https://github.com/mgp25/Instagram-API/blob/6939ba1aadcbddf7277b5a28a6d09715d5632c07/src/Request/Push.php#L32 - A method to register obtained Push token.

It might sound hard, but it is just a couple of days of coding, since you have all info at your hands.

**Pull request merged**
