### PR TITLE
Update SharePrefillResponse.php

### PR DESCRIPTION
**Pull request by Juan-de-Costa-Rica**
JSON Mapper throwing an error on this response

### CODE REVIEW

**Comment by mgp25** [comment]
@Juan-de-Costa-Rica please post debug log response to verify this PR update.

Regards

**Comment by Juan-de-Costa-Rica** [comment]
Error:
```
PHP Fatal error:  Uncaught LazyJsonMapper\Exception\LazyJsonMapperException: Unable to convert data to stdClass: Bad JSON property definitions in "InstagramAPI\Response\SharePrefillResponse": (['Unable to convert non-object-array inner value for property "ranking" into class "\InstagramAPI\Response\Model\Ranking".']). in /home/juan/Projects/instagram/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php:1174
Stack trace:
#0 /home/juan/Projects/instagram/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php(1340): LazyJsonMapper\LazyJsonMapper->exportObjectDataCopy('stdClass')
#1 /home/juan/Projects/instagram/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php(1397): LazyJsonMapper\LazyJsonMapper->asJson(448, 512)
#2 /home/juan/Projects/instagram/InstagramAPI-Testing/test.php(17): LazyJsonMapper\LazyJsonMapper->printJson()
#3 {main}
  thrown in /home/juan/Projects/instagram/vendor/lazyjsonmapper/lazyjsonmapper/src/LazyJsonMapper.php on line 1174
```
From:
```
try {
    $resp = $ig->people->getSharePrefill();
    $resp->printJson();
} catch (InstagramAPI\Exception $e) {
    echo $e->getMessage();
}
```

**Comment by mgp25** [comment]
I meant the API response, so I can verify the response matches the new response class.

**Comment by Juan-de-Costa-Rica** [comment]
```
    "ranking": [
        {
            "view_name": "story_share_sheet",
            "score_map": {
                "16048352204768939109633690491222145869": {
                    "score": 0.032695151865482,
                    "entity_type": "thread"
                },
                "175414990579677109004420267917709780488": {
                    "score": 0.031283278018236,
                    "entity_type": "thread"
                },
                "340282366841710300949128273812190448594": {
                    "score": 0.027908753603697,
                    "entity_type": "thread"
                },
                "340282366841710300949128184001685619521": {
                    "score": 0.02313226647675,
                    "entity_type": "thread"
                },
                "340282366841710300949128174842901489429": {
                    "score": 0.022007651627064,
                    "entity_type": "thread"
                },
                "340282366841710300949128181003506482786": {
                    "score": 0.016926661133766,
                    "entity_type": "thread"
                },
                "340282366841710300949128297683103472347": {
                    "score": 0.016769152134657,
                    "entity_type": "thread"
                },
                "340282366841710300949128137487975366204": {
                    "score": 0.016731197014451,
                    "entity_type": "thread"
                },
                "340282366841710300949128296919441446251": {
                    "score": 0.013155949302018,
                    "entity_type": "thread"
                },
                "340282366841710300949128228135507366801": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128269049678470708": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128206477262511731": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128219922422493765": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128170456490547809": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128184848666483075": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "27005512627667268649751195977": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128262268871295112": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128185525730485132": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128225596346381385": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128226903182345557": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128179092914484884": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "201537934680147539072037409847461350513": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128154322271390746": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128205816842353209": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128176878059308269": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128230024376314407": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128139146798426287": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128135130506276109": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "6098348175086288534535308335": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128148783473297647": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                }
            },
            "expiration_ms": "100000"
        },
        {
            "view_name": "reshare_share_sheet",
            "score_map": {
                "16048352204768939109633690491222145869": {
                    "score": 0.032695151865482,
                    "entity_type": "thread"
                },
                "175414990579677109004420267917709780488": {
                    "score": 0.031283278018236,
                    "entity_type": "thread"
                },
                "340282366841710300949128273812190448594": {
                    "score": 0.027908753603697,
                    "entity_type": "thread"
                },
                "340282366841710300949128184001685619521": {
                    "score": 0.02313226647675,
                    "entity_type": "thread"
                },
                "340282366841710300949128174842901489429": {
                    "score": 0.022007651627064,
                    "entity_type": "thread"
                },
                "340282366841710300949128181003506482786": {
                    "score": 0.016926661133766,
                    "entity_type": "thread"
                },
                "340282366841710300949128297683103472347": {
                    "score": 0.016769152134657,
                    "entity_type": "thread"
                },
                "340282366841710300949128137487975366204": {
                    "score": 0.016731197014451,
                    "entity_type": "thread"
                },
                "340282366841710300949128296919441446251": {
                    "score": 0.013155949302018,
                    "entity_type": "thread"
                },
                "340282366841710300949128228135507366801": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128269049678470708": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128206477262511731": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128219922422493765": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128170456490547809": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128184848666483075": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "27005512627667268649751195977": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128262268871295112": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128185525730485132": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128225596346381385": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128226903182345557": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128179092914484884": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "201537934680147539072037409847461350513": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128154322271390746": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128205816842353209": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128176878059308269": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128230024376314407": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128139146798426287": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128135130506276109": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "6098348175086288534535308335": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                },
                "340282366841710300949128148783473297647": {
                    "score": 0.013153071515262,
                    "entity_type": "thread"
                }
            },
            "expiration_ms": "100000"
        }
    ],
```

**Comment by mgp25** [comment]
Thanks

**Pull request merged**
