### PR TITLE
Some new feature

### PR DESCRIPTION
**Pull request by juampi92**
SMS Verification Challenge
Anti-flood wait feature
TagRelated service
FriendshipStatus && Friendships ShowMany services

Sorry for the formatting fixes, I'm using phpfmt on SublimeText3.
Sorry for deleting all the initial requests when logged in, but I couldn't figure out why they were there.

### CODE REVIEW

**Comment by juampi92** [comment]
Okay, so I'm configuring my phpformatter with StyleCli standards then...

**Comment by mgp25** [comment]
@juampi92 add the initial requests back if possible. If you want to keep improving this api, ill give you a tool i made for getting requests and you will see where it come from

**Comment by juampi92** [comment]
@mgp25 Ok, I'll add them. I found a way to configure phpfmt like your repo, so I'll do that. 
What are the initial requests? For testing? Don't you think I'll be better to have a test.php file or something? Just saying

**Comment by mgp25** [comment]
@juampi92 initial requests are emulating the same requests the app does. I did put them for a reason xd

**Comment by juampi92** [comment]
@mgp25 Oh... haha now I'm convinced 😄

**Comment by mgp25** [comment]
@juampi92 send the PR when its ready

**Pull request closed without merging**
