### PR TITLE
Add exception codes

### PR DESCRIPTION
**Pull request by frrakn**
Want to standardize how Exceptions are thrown and handled here.

### CODE REVIEW

**Comment by jpmoney5065** [comment]
what about:
`checkpoint_challenge_required`
`following the max limit`
`disabled`
`sentry_block`
`invalid_user`

**Comment by frrakn** [comment]
I haven't personally seen these errors but if you can provide me the text /
regex I will include in this PR.

**Comment by jpmoney5065** [comment]
Disabled account response:
`{"message":"Your account has been disabled for violating our terms. Learn how you may be able to restore your account.","error_type":"inactive user","status":"fail","help_url":"https:\/\/help.instagram.com\/521372114683554"}`

Different checkpoint responses:
`{"status":"fail","lock":true,"message":"checkpoint_required","error_type":"checkpoint_challenge_required","checkpoint_url":"https:\/\/i.instagram.com\/challenge\/4359495813\/crnJe3bxxx\/"}`

 `{"status":"fail","checkpoint_url":"https:\/\/i.instagram.com\/challenge\/?challenge_type=signup&guid=a4dd0deb272e480b970d7bxxxxxxxxxx","lock":true,"message":"checkpoint_required"}`


and I don't have the responses for `following the max limit`, `sentry_block` or `invalid_user` right now, but I have caught them with those text entries.

**Comment by frrakn** [comment]
@jpmoney5065, I included disabled account, sentry block, and invalid user in #888.

The `checkpoint_required` regex will handle all of the checkpoint responses bc it goes off of the `message` field.

**Pull request merged**
