### PR TITLE
ImageAutoResizer: fixed aspectRatio round problem

### PR DESCRIPTION
**Pull request by safhome**
This patch solves a problem with images whose dimensions are very close to those required for Instagram. Sometimes result image has invalid proportions because of 1 additional pixel, which is produced by ImageAutoResizer on divisions without rounding of result value.

### CODE REVIEW

**Comment by SteveJobzniak** [comment]
Thanks but hmm, this looks wrong. You are replacing a correct, accurate aspect ratio calculation with the same plus truncated rounding rounding, and you are replacing the rotated aspect ratio inversion with an incorrect one that is no longer rotated. Why those two changes to _aspectRatio calculation?

As for the final width-height calculation changes, I guess you mean that our high-precision aspect ratio can lead to $height being 1 pixel more than allowed? I really don't understand that either because we use floor() to round downwards.

Please just give a detailed explanation of the exact issue. What are the original image dimensions and ehat is the final result, and what is wrong about the final result? When I understand the issue, if there is an issue, I will fix it cleanly.

**Comment by SteveJobzniak** [comment]
Closed? I guess there is no issue then?

**Comment by valga** [comment]
I can confirm the issue with ImageAutoResizer. It happens when aspect ratio is very close to the maximum one. And the fix is [here](https://github.com/mgp25/Instagram-API/pull/1085/commits/cefb72c4755562d97172857176d46f2bd8dc27db). But I didn't test it.

**Comment by SteveJobzniak** [comment]
@valga Hmm, well that's probably not right either. Because the "else"-block deals with images that are either too tall (portrait) or too wide (landscape). With this proposed change, I think we lose support for handling images that are too tall?

So if an image is 100px wide and 5000px tall, it would get an aspect ratio of 100/5000 = 0.02.

And since that number is not == 1, we go to this "else".

Then this "else" checks "if width(100px) > max_width: do stuff", but does nothing since width is no problem.

I don't know... It's been months since we worked on this code so I've forgotten how it works. But I have a vague memory that there was a reason why we placed the $height outside the "if width" check...

```php
} else {
--
  |   |             // If > 1: Landscape (wider than tall). Limit by width.
  |   |             // If < 1: Portrait (taller than wide). Limit by width.
  |   |             // NOTE: Maximum "allowed" height is 1350, which is EXACTLY what you
  |   |             // get with a maxwidth of 1080 / 0.8 (4:5 aspect ratio). Instagram
  |   |             // enforces width & aspect ratio, which in turn auto-decides height.
  |   |             if ($width > self::MAX_WIDTH) {
  |   |                           $width = self::MAX_WIDTH;
  |   |                           $height = floor($width / $aspectRatio); // ++
  |   |             }
  |   |             $height = floor($width / $aspectRatio); // --
  |   | }
```

**Comment by valga** [comment]
> With this proposed change, I think we lose support for handling images that are too tall?

I don't think that we lose anything, because that height calculation is really needed only on width change.

> Do any of you two have any example image (or dimensions) that we can test the math with?

Pick one from this list:
```
1024x101 => 192x100 (1.920)
1024x102 => 194x101 (1.921)
1024x103 => 196x102 (1.922)
1024x104 => 198x103 (1.922)
1024x105 => 200x104 (1.923)
1024x106 => 202x105 (1.924)
1024x107 => 204x106 (1.925)
1024x108 => 206x107 (1.925)
1024x109 => 208x108 (1.926)
1024x110 => 210x109 (1.927)
1024x111 => 212x110 (1.927)
1024x112 => 213x111 (1.919)
1024x113 => 215x112 (1.920)
1024x114 => 217x113 (1.920)
1024x115 => 219x114 (1.921)
1024x116 => 221x115 (1.922)
1024x117 => 223x116 (1.922)
1024x118 => 225x117 (1.923)
1024x119 => 227x118 (1.924)
1024x120 => 229x119 (1.924)
1024x121 => 231x120 (1.925)
1024x122 => 233x121 (1.926)
1024x123 => 234x122 (1.918)
1024x124 => 236x123 (1.919)
1024x125 => 238x124 (1.919)
1024x126 => 240x125 (1.920)
1024x127 => 242x126 (1.921)
1024x128 => 244x127 (1.921)
1024x129 => 246x128 (1.922)
1024x130 => 248x129 (1.922)
1024x131 => 250x130 (1.923)
1024x132 => 252x131 (1.924)
1024x133 => 254x132 (1.924)
1024x134 => 255x133 (1.917)
1024x135 => 257x134 (1.918)
1024x136 => 259x135 (1.919)
1024x137 => 261x136 (1.919)
1024x138 => 263x137 (1.920)
1024x139 => 265x138 (1.920)
1024x140 => 267x139 (1.921)
1024x141 => 269x140 (1.921)
1024x142 => 271x141 (1.922)
1024x143 => 273x142 (1.923)
1024x144 => 275x143 (1.923)
1024x145 => 276x144 (1.917)
1024x146 => 278x145 (1.917)
1024x147 => 280x146 (1.918)
1024x148 => 282x147 (1.918)
1024x149 => 284x148 (1.919)
1024x150 => 286x149 (1.919)
1024x151 => 288x150 (1.920)
1024x152 => 290x151 (1.921)
1024x153 => 292x152 (1.921)
1024x154 => 294x153 (1.922)
1024x155 => 296x154 (1.922)
1024x156 => 297x155 (1.916)
1024x157 => 299x156 (1.917)
1024x158 => 301x157 (1.917)
1024x159 => 303x158 (1.918)
1024x160 => 305x159 (1.918)
1024x161 => 307x160 (1.919)
1024x162 => 309x161 (1.919)
1024x163 => 311x162 (1.920)
1024x164 => 313x163 (1.920)
1024x165 => 315x164 (1.921)
1024x166 => 317x165 (1.921)
1024x167 => 318x166 (1.916)
1024x168 => 320x167 (1.916)
1024x169 => 322x168 (1.917)
1024x170 => 324x169 (1.917)
1024x171 => 326x170 (1.918)
1024x172 => 328x171 (1.918)
1024x173 => 330x172 (1.919)
1024x174 => 332x173 (1.919)
1024x175 => 334x174 (1.920)
1024x176 => 336x175 (1.920)
1024x177 => 338x176 (1.920)
1024x178 => 339x177 (1.915)
1024x179 => 341x178 (1.916)
1024x180 => 343x179 (1.916)
1024x181 => 345x180 (1.917)
1024x182 => 347x181 (1.917)
1024x183 => 349x182 (1.918)
1024x184 => 351x183 (1.918)
1024x185 => 353x184 (1.918)
1024x186 => 355x185 (1.919)
1024x187 => 357x186 (1.919)
1024x188 => 359x187 (1.920)
1024x189 => 360x188 (1.915)
1024x190 => 362x189 (1.915)
1024x191 => 364x190 (1.916)
1024x192 => 366x191 (1.916)
1024x193 => 368x192 (1.917)
1024x194 => 370x193 (1.917)
1024x195 => 372x194 (1.918)
1024x196 => 374x195 (1.918)
1024x197 => 376x196 (1.918)
1024x198 => 378x197 (1.919)
1024x199 => 380x198 (1.919)
1024x201 => 383x200 (1.915)
1024x202 => 385x201 (1.915)
1024x203 => 387x202 (1.916)
1024x204 => 389x203 (1.916)
1024x205 => 391x204 (1.917)
1024x206 => 393x205 (1.917)
1024x207 => 395x206 (1.917)
1024x208 => 397x207 (1.918)
1024x209 => 399x208 (1.918)
1024x210 => 401x209 (1.919)
1024x211 => 403x210 (1.919)
1024x212 => 404x211 (1.915)
1024x213 => 406x212 (1.915)
1024x214 => 408x213 (1.915)
1024x215 => 410x214 (1.916)
1024x216 => 412x215 (1.916)
1024x217 => 414x216 (1.917)
1024x218 => 416x217 (1.917)
1024x219 => 418x218 (1.917)
1024x220 => 420x219 (1.918)
1024x221 => 422x220 (1.918)
1024x222 => 424x221 (1.919)
1024x223 => 425x222 (1.914)
1024x224 => 427x223 (1.915)
1024x225 => 429x224 (1.915)
1024x226 => 431x225 (1.916)
1024x227 => 433x226 (1.916)
1024x228 => 435x227 (1.916)
1024x229 => 437x228 (1.917)
1024x230 => 439x229 (1.917)
1024x231 => 441x230 (1.917)
1024x232 => 443x231 (1.918)
1024x233 => 445x232 (1.918)
1024x234 => 446x233 (1.914)
1024x235 => 448x234 (1.915)
1024x236 => 450x235 (1.915)
1024x237 => 452x236 (1.915)
1024x238 => 454x237 (1.916)
1024x239 => 456x238 (1.916)
1024x240 => 458x239 (1.916)
1024x241 => 460x240 (1.917)
1024x242 => 462x241 (1.917)
1024x243 => 464x242 (1.917)
1024x244 => 466x243 (1.918)
1024x245 => 467x244 (1.914)
1024x246 => 469x245 (1.914)
1024x247 => 471x246 (1.915)
1024x248 => 473x247 (1.915)
1024x249 => 475x248 (1.915)
1024x250 => 477x249 (1.916)
1024x251 => 479x250 (1.916)
1024x252 => 481x251 (1.916)
1024x253 => 483x252 (1.917)
1024x254 => 485x253 (1.917)
1024x255 => 487x254 (1.917)
1024x256 => 488x255 (1.914)
1024x257 => 490x256 (1.914)
1024x258 => 492x257 (1.914)
1024x259 => 494x258 (1.915)
1024x260 => 496x259 (1.915)
1024x261 => 498x260 (1.915)
1024x262 => 500x261 (1.916)
1024x263 => 502x262 (1.916)
1024x264 => 504x263 (1.916)
1024x265 => 506x264 (1.917)
1024x266 => 508x265 (1.917)
1024x267 => 509x266 (1.914)
1024x268 => 511x267 (1.914)
1024x269 => 513x268 (1.914)
1024x270 => 515x269 (1.914)
1024x271 => 517x270 (1.915)
1024x272 => 519x271 (1.915)
1024x273 => 521x272 (1.915)
1024x274 => 523x273 (1.916)
1024x275 => 525x274 (1.916)
1024x276 => 527x275 (1.916)
1024x277 => 529x276 (1.917)
1024x278 => 530x277 (1.913)
1024x279 => 532x278 (1.914)
1024x280 => 534x279 (1.914)
1024x281 => 536x280 (1.914)
1024x282 => 538x281 (1.915)
1024x283 => 540x282 (1.915)
1024x284 => 542x283 (1.915)
1024x285 => 544x284 (1.915)
1024x286 => 546x285 (1.916)
1024x287 => 548x286 (1.916)
1024x288 => 550x287 (1.916)
1024x289 => 551x288 (1.913)
1024x290 => 553x289 (1.913)
1024x291 => 555x290 (1.914)
1024x292 => 557x291 (1.914)
1024x293 => 559x292 (1.914)
1024x294 => 561x293 (1.915)
1024x295 => 563x294 (1.915)
1024x296 => 565x295 (1.915)
1024x297 => 567x296 (1.916)
1024x298 => 569x297 (1.916)
1024x299 => 571x298 (1.916)
1024x301 => 574x300 (1.913)
1024x302 => 576x301 (1.914)
1024x303 => 578x302 (1.914)
1024x304 => 580x303 (1.914)
1024x305 => 582x304 (1.914)
1024x306 => 584x305 (1.915)
1024x307 => 586x306 (1.915)
1024x308 => 588x307 (1.915)
1024x309 => 590x308 (1.916)
1024x310 => 592x309 (1.916)
1024x311 => 594x310 (1.916)
1024x312 => 595x311 (1.913)
1024x313 => 597x312 (1.913)
1024x314 => 599x313 (1.914)
1024x315 => 601x314 (1.914)
1024x316 => 603x315 (1.914)
1024x317 => 605x316 (1.915)
1024x318 => 607x317 (1.915)
1024x319 => 609x318 (1.915)
1024x320 => 611x319 (1.915)
1024x321 => 613x320 (1.916)
1024x322 => 615x321 (1.916)
1024x323 => 616x322 (1.913)
1024x324 => 618x323 (1.913)
1024x325 => 620x324 (1.914)
1024x326 => 622x325 (1.914)
1024x327 => 624x326 (1.914)
1024x328 => 626x327 (1.914)
1024x329 => 628x328 (1.915)
1024x330 => 630x329 (1.915)
1024x331 => 632x330 (1.915)
1024x332 => 634x331 (1.915)
1024x333 => 636x332 (1.916)
1024x334 => 637x333 (1.913)
1024x335 => 639x334 (1.913)
1024x336 => 641x335 (1.913)
1024x337 => 643x336 (1.914)
1024x338 => 645x337 (1.914)
1024x339 => 647x338 (1.914)
1024x340 => 649x339 (1.914)
1024x341 => 651x340 (1.915)
1024x342 => 653x341 (1.915)
1024x343 => 655x342 (1.915)
1024x344 => 657x343 (1.915)
1024x345 => 658x344 (1.913)
1024x346 => 660x345 (1.913)
1024x347 => 662x346 (1.913)
1024x348 => 664x347 (1.914)
1024x349 => 666x348 (1.914)
1024x350 => 668x349 (1.914)
1024x351 => 670x350 (1.914)
1024x352 => 672x351 (1.915)
1024x353 => 674x352 (1.915)
1024x354 => 676x353 (1.915)
1024x355 => 678x354 (1.915)
1024x356 => 679x355 (1.913)
1024x357 => 681x356 (1.913)
1024x358 => 683x357 (1.913)
1024x359 => 685x358 (1.913)
1024x360 => 687x359 (1.914)
1024x361 => 689x360 (1.914)
1024x362 => 691x361 (1.914)
1024x363 => 693x362 (1.914)
1024x364 => 695x363 (1.915)
1024x365 => 697x364 (1.915)
1024x366 => 699x365 (1.915)
1024x367 => 700x366 (1.913)
1024x368 => 702x367 (1.913)
1024x369 => 704x368 (1.913)
1024x370 => 706x369 (1.913)
1024x371 => 708x370 (1.914)
1024x372 => 710x371 (1.914)
1024x373 => 712x372 (1.914)
1024x374 => 714x373 (1.914)
1024x375 => 716x374 (1.914)
1024x376 => 718x375 (1.915)
1024x377 => 720x376 (1.915)
1024x378 => 721x377 (1.912)
1024x379 => 723x378 (1.913)
1024x380 => 725x379 (1.913)
1024x381 => 727x380 (1.913)
1024x382 => 729x381 (1.913)
1024x383 => 731x382 (1.914)
1024x384 => 733x383 (1.914)
1024x385 => 735x384 (1.914)
1024x386 => 737x385 (1.914)
1024x387 => 739x386 (1.915)
1024x388 => 741x387 (1.915)
1024x389 => 742x388 (1.912)
1024x390 => 744x389 (1.913)
1024x391 => 746x390 (1.913)
1024x392 => 748x391 (1.913)
1024x393 => 750x392 (1.913)
1024x394 => 752x393 (1.913)
1024x395 => 754x394 (1.914)
1024x396 => 756x395 (1.914)
1024x397 => 758x396 (1.914)
1024x398 => 760x397 (1.914)
1024x399 => 762x398 (1.915)
1024x401 => 765x400 (1.913)
1024x402 => 767x401 (1.913)
1024x403 => 769x402 (1.913)
1024x404 => 771x403 (1.913)
1024x405 => 773x404 (1.913)
1024x406 => 775x405 (1.914)
1024x407 => 777x406 (1.914)
1024x408 => 779x407 (1.914)
1024x409 => 781x408 (1.914)
1024x410 => 783x409 (1.914)
1024x411 => 785x410 (1.915)
1024x412 => 786x411 (1.912)
1024x413 => 788x412 (1.913)
1024x414 => 790x413 (1.913)
1024x415 => 792x414 (1.913)
1024x416 => 794x415 (1.913)
1024x417 => 796x416 (1.913)
1024x418 => 798x417 (1.914)
1024x419 => 800x418 (1.914)
1024x420 => 802x419 (1.914)
1024x421 => 804x420 (1.914)
1024x422 => 806x421 (1.914)
1024x423 => 807x422 (1.912)
1024x424 => 809x423 (1.913)
1024x425 => 811x424 (1.913)
1024x426 => 813x425 (1.913)
1024x427 => 815x426 (1.913)
1024x428 => 817x427 (1.913)
1024x429 => 819x428 (1.914)
1024x430 => 821x429 (1.914)
1024x431 => 823x430 (1.914)
1024x432 => 825x431 (1.914)
1024x433 => 827x432 (1.914)
1024x434 => 828x433 (1.912)
1024x435 => 830x434 (1.912)
1024x436 => 832x435 (1.913)
1024x437 => 834x436 (1.913)
1024x438 => 836x437 (1.913)
1024x439 => 838x438 (1.913)
1024x440 => 840x439 (1.913)
1024x441 => 842x440 (1.914)
1024x442 => 844x441 (1.914)
1024x443 => 846x442 (1.914)
1024x444 => 848x443 (1.914)
1024x445 => 849x444 (1.912)
1024x446 => 851x445 (1.912)
1024x447 => 853x446 (1.913)
1024x448 => 855x447 (1.913)
1024x449 => 857x448 (1.913)
1024x450 => 859x449 (1.913)
1024x451 => 861x450 (1.913)
1024x452 => 863x451 (1.914)
1024x453 => 865x452 (1.914)
1024x454 => 867x453 (1.914)
1024x455 => 869x454 (1.914)
1024x456 => 870x455 (1.912)
1024x457 => 872x456 (1.912)
1024x458 => 874x457 (1.912)
1024x459 => 876x458 (1.913)
1024x460 => 878x459 (1.913)
1024x461 => 880x460 (1.913)
1024x462 => 882x461 (1.913)
1024x463 => 884x462 (1.913)
1024x464 => 886x463 (1.914)
1024x465 => 888x464 (1.914)
1024x466 => 890x465 (1.914)
1024x467 => 891x466 (1.912)
1024x468 => 893x467 (1.912)
1024x469 => 895x468 (1.912)
1024x470 => 897x469 (1.913)
1024x471 => 899x470 (1.913)
1024x472 => 901x471 (1.913)
1024x473 => 903x472 (1.913)
1024x474 => 905x473 (1.913)
1024x475 => 907x474 (1.914)
1024x476 => 909x475 (1.914)
1024x477 => 911x476 (1.914)
1024x478 => 912x477 (1.912)
1024x479 => 914x478 (1.912)
1024x480 => 916x479 (1.912)
1024x481 => 918x480 (1.913)
1024x482 => 920x481 (1.913)
1024x483 => 922x482 (1.913)
1024x484 => 924x483 (1.913)
1024x485 => 926x484 (1.913)
1024x486 => 928x485 (1.913)
1024x487 => 930x486 (1.914)
1024x488 => 932x487 (1.914)
1024x489 => 933x488 (1.912)
1024x490 => 935x489 (1.912)
1024x491 => 937x490 (1.912)
1024x492 => 939x491 (1.912)
1024x493 => 941x492 (1.913)
1024x494 => 943x493 (1.913)
1024x495 => 945x494 (1.913)
1024x496 => 947x495 (1.913)
1024x497 => 949x496 (1.913)
1024x498 => 951x497 (1.913)
1024x499 => 953x498 (1.914)
1024x501 => 956x500 (1.912)
1024x502 => 958x501 (1.912)
1024x503 => 960x502 (1.912)
1024x504 => 962x503 (1.913)
1024x505 => 964x504 (1.913)
1024x506 => 966x505 (1.913)
1024x507 => 968x506 (1.913)
1024x508 => 970x507 (1.913)
1024x509 => 972x508 (1.913)
1024x510 => 974x509 (1.914)
1024x511 => 976x510 (1.914)
1024x512 => 977x511 (1.912)
1024x513 => 979x512 (1.912)
1024x514 => 981x513 (1.912)
1024x515 => 983x514 (1.912)
1024x516 => 985x515 (1.913)
1024x517 => 987x516 (1.913)
1024x518 => 989x517 (1.913)
1024x519 => 991x518 (1.913)
1024x520 => 993x519 (1.913)
1024x521 => 995x520 (1.913)
1024x522 => 997x521 (1.914)
1024x523 => 998x522 (1.912)
1024x524 => 1000x523 (1.912)
1024x525 => 1002x524 (1.912)
1024x526 => 1004x525 (1.912)
1024x527 => 1006x526 (1.913)
1024x528 => 1008x527 (1.913)
1024x529 => 1010x528 (1.913)
1024x530 => 1012x529 (1.913)
1024x531 => 1014x530 (1.913)
1024x532 => 1016x531 (1.913)
1024x533 => 1018x532 (1.914)
1024x534 => 1019x533 (1.912)
1024x535 => 1021x534 (1.912)
1024x536 => 1023x535 (1.912)
```

**Comment by safhome** [comment]
My real image.
Original width: 594
Original height: 187
Original aspectRatio: 3.1764705882353
Result width: 357
Result height: 186
Result aspectRatio: 1.91
REAL Result aspectRatio: 1.9193548387097
So I can't post such image with example script because it says:
Instagram only accepts media with aspect ratios between 0.80 and 1.91. Your file "/tmp/IMGq0KPAc" has a 1.92 aspect ratio.

I'v closed this pull request because I want to reseach this issue and try to make the right decision.

**Comment by SteveJobzniak** [comment]
Hmm, I see... so the resizer can create images that are a little bit more than 1.91 ratio. Ouch. Well this seems to be a head-scratching scenario. We need to think about this some more...

**Comment by SteveJobzniak** [comment]
- Instagram enforces `width <= max-width` (must be within limits)
- Height is not restricted at all
- Aspect ratio is restricted (must be within limits; which is how height becomes restricted)

So the solution should:
- `if width > max-width; width = max-width`
- `recalculate height based on the final width, so that aspect-ratio is never over 1.91`

**Comment by LanchaBasualdo** [comment]
Sorry guys, just tu catch up. This condition applies to all types o media right?

**Comment by safhome** [comment]
I've tested algorithm and result:

code
                                if ($aspectRatio > 1) {
					$height = ceil($width / $aspectRatio);
				} else {
					$height = floor($width / $aspectRatio);
				}

resulted to no errors with tall and wide images. Sence of this change: if we have tall image, then it's height must be <= calculated (so using floor), and if we have wide image, then it's height must be >= calculated (otherwise aspectRatio will be out of range), so we need to use ceil.

**Comment by safhome** [comment]
I've updated my request to include only code above.

**Comment by SteveJobzniak** [comment]
Hmm, @safhome that's a great find and is on the right track! The if/else could be written nicer with ternary though. But that's a later question.

It seems like you may have found the right algorithm and the reason for the error, at least!


Take this example:

1080 px wide / 1.91 aspect ratio (max allowed) = 565.445026178 px height is the max allowed.

Your code is doing ceil() if aspect ratio is > 1, so your code is turning this height to 566.
1080/566 = 1.908127208 aspect ratio = legal.

If we had done floor(), which the old code always does, then it would have been 1080/565 = 1.911504425 = illegal (above 1.91 ratio).


Take this other example:

902px wide / 0.8 aspect ratio (min allowed) = 1127.5 px height is the max allowed.

Your code is doing floor() if aspect ratio is , 1, so your code is turning this height to 1127.
902/1127 = 0.800354925 aspect ratio = legal.


So at first glance, this seems correct. We'll have to do a closer analysis before merging. But I am guessing this is indeed the correct fix. Thanks a lot for researching!

**Comment by SteveJobzniak** [comment]
I went in and edited the pull request. It'll have to be squashed when we merge it.

Anyway, I added some algorithm comments so we understand the reason in the future:

https://github.com/mgp25/Instagram-API/pull/1404/files

But before merging, this needs testing and verification.

**Comment by SteveJobzniak** [comment]
I worry that perhaps there's many cases where ceil() hurts the image by stretching it somehow (for example taking a 500px tall input image and stretching it to 501). I am too tired think about that right now, so leaving this open until those questions are solved.

It is _possible_ that an even more correct solution would be to always use floor(), and to instead of just touching height, we should also be limiting width. Hmm. For example, the 1.91 ratio example above of 1080px wide * 565.44px tall, could be solved as 1079 * 565 (1.909734513 ratio), which means chopping away 1 pixel from each side of the image...

Chopping is better than extending/stretching. Hmm....

So perhaps THIS is the correct algorithm instead:

```php
$aspectRatio = 1.91; // desired ratio
$width = 1080; // input width
$height = 565.55; // input height

if ($width > self::MAX_WIDTH) {
    $width = self::MAX_WIDTH;
}
$height = floor($width / $aspectRatio); // 565
$width = floor($height * $aspectRatio); // 1079

// Result: 1079 / 565 = 1.909734513 ratio.
```

**Comment by SteveJobzniak** [comment]
Bleh, I wanted to check really quickly before bed and wrote some super ugly test code... More investigation is needed:

```php
<?php

function foo(
    $targetRatio = 0.8,
    $debugAll = false)
{
    for ($width = 1; $width <= 1080; ++$width) {
        for ($height = 1; $height <= 1080; ++$height) {
            // Calculate final dimensions to chop image down to.
            if ($targetRatio < 1) { // tall portrait
                $final_width = floor($height * $targetRatio);
                $final_height = floor($final_width / $targetRatio);
            } else { // wide landscape
                $final_height = floor($width / $targetRatio);
                $final_width = floor($final_height * $targetRatio);
            }

            // Avoid zero dimensions. NOTE: Could probably screw ratio.
            if ($final_width < 1) $final_width = 1;
            if ($final_height < 1) $final_height = 1;

            // Verify the final ratio
            $final_ratio = $final_width / $final_height;
            if ($final_ratio < 0.8 || $final_ratio > 1.91) {
                printf("BAD RATIO: %f\n", $final_ratio); // NEVER HAPPENS!
            }
            if ($debugAll) printf("%s x %s = %f\n", $final_width, $final_height, $final_ratio);
        }
    }
}

foo(0.8);
foo(1.91);
```

Note that the "BAD RATIO" code never runs. So this algorithm may be on the right track...

Other investigators are welcome to join in and help figure this out. More minds = better.

**Comment by mgp25** [comment]
@SteveJobzniak if everything okay, after this PR is done and after sending a couple of commits i have and recheking flow, i guess release 3.0 is ready to be pushed

**Comment by safhome** [comment]
I think that you are looking for a complex answer to a simple question. If the result of division is not an integer, then any rounding option and any calculation will give only an approximate value for the aspect ratio, so your image wil be stretched vertically or horisontally, but only for less then 1 pixel. Therefore, here we need to solve only the problem of establishing the correct aspect ratio, and only.

**Comment by valga** [comment]
@SteveJobzniak I can confirm that ceil() fixes the issue for landscape photos. 

And there is a simple explanation for this: `floor($height)` makes aspect ratio _bigger_, because `$height` is going smaller. While it is ok for lowest allowed ratio (0.8), it will fail when we are close to highest allowed ratio (1.91). And `ceil($height)` fixes it, because it makes aspect ratio _smaller_.

**Comment by SteveJobzniak** [comment]
@mgp25 Wohoo that is super fantastic news after months of work! Will feel good to finally have 3.0 out!

@safhome Well, the reason I was trying so hard is because imagine that we are getting an input image that is close to 1.91 already, and is 956px wide and 500px tall. That's a ratio of 956/500 = 1.912.

So with your proposed algorithm we do:
- Width less than maxwidth? Ok, do not touch width.
- Height must now be ceil(width / targetAspectRatio), meaning ceil(956/1.91), so height becomes 501.
- Then we copy to target image with resampling/stretching: 956x500 image becomes 956x501 image. So if any sharp, computer-generated text or clipart is on the image, the result image will become blurry (we resize every pixel by a tiny fraction to stretch by 1px taller, thus blurring the whole image!)...

My proposed (unfinished) algorithm would instead do:
- `$height = floor($width / $targetRatio);` aka `$height = floor(956 / 1.91);` meaning 500px tall.
- `$width = floor($height * $targetRatio);` aka `$width = floor(500 * 1.91);` meaning 955px wide.
- Final result: 956x500 image (ratio 1.912) becomes 955x500 image (ratio 1.91), and we just have to chop 1 pixel from the width. No stretching is necessary to resample/extend the image.

@valga Yeah that's what I realized yesterday. Then I started investigating if we can rewrite it with floor() to always generate cropping, never stretching. And I had some algorithms for that as you saw above (final post).

@mgp25 This needs more research. It is not ready for merge yet.

**Comment by valga** [comment]
@SteveJobzniak You are going too deep. Take a look at [the original code](https://github.com/valga/Instagram-API/blob/59e3798dbd082b10fa93b7f5a23f682e02a3c803/src/Utils/ImageAutoResizer.php#L420). It has some flaws, but the main idea is that you don't need to recalculate height every time. You need to do that only when you changed the width. In all other case you already have a valid height.

So all you need is to move height calculation into `$width = self::MAX_WIDTH;` block.

**Comment by SteveJobzniak** [comment]
@valga Hmm, okay. Sometime today I will read carefully and in-depth the code above the section we're working on. The code above affects $width and $height already, higher up in the code. So I guess what I am trying to solve (cropping instead of extending) is already done in that earlier code.

**Comment by safhome** [comment]
@SteveJobzniak You can test the whole algorithm (not only my change) with your values 956/500 = 1.912. Results of my test: 500x956 (1.912) => 500x955 (1.91)
I also checked for boundary values:
565x1081 (1.9132743362832) => 565x1079 (1.9097345132743)
564x1081 (1.9166666666667) => 564x1077 (1.9095744680851)
565x1080 (1.9115044247788) => 565x1079 (1.9097345132743)
565x1081 (1.9132743362832) => 565x1079 (1.9097345132743)
566x1081 (1.9098939929329) => 566x1080 (1.9081272084806)
563x1080 (1.9182948490231) => 563x1075 (1.9094138543517)
No stretching.

**Comment by SteveJobzniak** [comment]
@safhome Aspect ratio is width divided by height. The 1st number in "1x2" is width, the 2nd is height. So your examples don't make sense.

Anyway I'll read the whole code in detail soon. Very tired at the moment.

**Comment by safhome** [comment]
@SteveJobzniak Swap numbers (i.e. 565x1081 -> 1081x565). When I look at the code, I haven't first and second numbers, I have width and height, and when I make test, I've print "{$h1}x{$w1} ($a1) => {$height}x{$width} ($a2)" because the position of the number means nothing to me. I'm sorry if I misled you.

**Comment by SteveJobzniak** [comment]
@valga I am working on the re-review of all current class code, and possibly found the main reason for the bug.

It's in the earlier sections, for example this one:

```php
        if ($this->_minAspectRatio !== null && $this->_aspectRatio < $this->_minAspectRatio) {
            $height = floor($this->_width / $this->_minAspectRatio);
            $aspectRatio = $this->_minAspectRatio;
```

Let's take this example:
- `$this->_width = 501` and `$this->_height = 2001`, which means original aspect ratio is `0.250374813`, which triggers this first code section.
- `$height = floor($this->_width / $this->_minAspectRatio);` which means: `$height = floor(501 / 0.8); // 626px height`
- `$aspectRatio = $this->_minAspectRatio; // 0.8`...
- But... hey!! That's false. If we do the new dimensions, and calculate the actual new aspect ratio, we get: `$aspectRatio = $width / $height;`, meaning `501 / 626`, meaning `0.800319489`. It is NOT `0.8`.

So regardless of what we do with the rest of the algorithm, I will change all `$aspectRatio = ...` lines (there's 3 of them) in the processing algorithm, to just be a single line that calculates the new ratio from the new width / height...

**Comment by valga** [comment]
> I will change all `$aspectRatio = ...` lines (there's 3 of them) in the processing algorithm, to just be a single line that calculates the real new ratio from the new width / height... 

Don't do that, because it will lead to undersized images. Just leave aspect ratio calculation as is.

Let me explain everything in details. We have 2 issues:
1. We must recalculate height only when we do a resize. Consider the example from above: when we have 956x500 image, all we have to do is change its width to 955. We don't have to change its height, because it is already perfect.
2. We must use `ceil()` for resized height of landscape photos. I hope I don't need to explain it.

So all we have to do is:
```php
if ($width > self::MAX_WIDTH) {
    $width = self::MAX_WIDTH;
    $height = $aspectRatio > 1 ? ceil($width / $aspectRatio) : floor($width / $aspectRatio);
}
```

**Comment by SteveJobzniak** [comment]
@valga Yep I understood the ceil(). I was only confused by the function's flow and the aspect calculation. After I realized that $aspectRatio is only used when we need to change the width to fit within Instagram's limits, I see why we don't want to re-calculate that value again. The variable name was a bit misleading (something like `$desiredAspectRatio` would have been clearer).

Anyway, I've reviewed the whole class again:

https://github.com/mgp25/Instagram-API/commit/317581ee0d3713bad31dc6b76d43077bf9046bc0

And finally added the fix we concluded in this thread, as well as lots of comment-rewrites to make it clearer in the future:

https://github.com/mgp25/Instagram-API/commit/92ccfc193e167798c42c53e731c1704ffc1594f7

Finally done! Thanks everyone for getting to the root of this bug! 👍

**Pull request closed without merging**
