### PR TITLE
Realtime: Refactor everything

### PR DESCRIPTION
**Pull request by valga**
Instagram is testing dynamic realtime subscriptions: for example, one can subscribe to some media stats (such as likes or video views counters) update or to notifications about people typing comments. Also, some new direct message commands were introduced.

But adding these new features will cause a lot of pain with current codebase, so this PR aims to make the Realtime client easier to maintain. Refer to the commits list for more details.

BC breaks:
1. All Realtime payload has been moved into a `\InstagramAPI\Realtime\Payload` namespace.
2. First parameter for the `unseen-count-update` event is now `$inbox`.
3. The `Realtime::updateSequenceId()` method has been renamed to `receiveOfflineMessages()` to match its purpose.

Replaces #1695.

### CODE REVIEW

**Comment by SteveJobzniak** [comment]
@valga Whew, with 69 changed files, 3700 added lines and 1700 removed lines, this must have been a lot of work to write. And a lot of work to review.

The code is very nice and makes a lot of sense. I love how you've finally defined handler interfaces for the various Realtime events, to give them a unified handle-method. Everything is cleaner and more modular now. I love it.

Merged without anything to change! :-)

**Comment by SteveJobzniak** [comment]
@mgp25 This was merged via rebase so that all commits come as a logical "package" at the top of the repo history.

But because of that we don't see the pull request message in the project history. So save this URL somewhere for when the day comes to write v4 release news. The first post here has a list of backwards compatibility breaking changes. `^_^`

**Comment by valga** [comment]
@SteveJobzniak I am fine with being the author of some commits in this repository.

**Comment by SteveJobzniak** [comment]
Alright, hehe. You are an incredible "author of some commits". ;-) ❤️

**Pull request merged**
